/**
 * Descriptions for atmosphere enums to help AI select the most appropriate options.
 */

export const ATMOSPHERE_DESCRIPTIONS = {
  envTheme: {
    fantasy: "Standard high fantasy atmosphere. Magical, colorful, and adventurous.",
    scifi: "Futuristic tech aesthetic. Clean, glowing blue accents, and metallic surfaces.",
    cyberpunk: "High-tech, low-life. Neon purples and cyans, rainy city vibes.",
    horror: "Dark, oppressive, and scary. Use for haunted ruins, ritual sites, or terrifying encounters.",
    mystery: "Noir/Investigative. Dim lighting, deep shadows, and an amber/gold warmth.",
    romance: "Romantic and soft. Pink and rose tones, gentle lighting.",
    royal: "Grand and luxurious. Rich reds and golds, palatial elegance.",
    wuxia: "Classical Chinese martial arts style. Ink-wash aesthetics and traditional colors.",
    demonic: "Hellish or demonic. Intense reds and oranges, infernal fire.",
    ethereal: "Otherworldly and sublime. Glowing whites, soft blues, and celestial light.",
    modern: "Contemporary day-to-day feel. Neutral colors, realistic lighting.",
    gold: "Desert, wealth, or divine glory. Dominant yellow and gold palette.",
    villain: "Menacing and cold. Dark greens and deep purples.",
    sepia: "Nostalgic, historical, or dream-like. Muted brown and tan tones.",
    rose: "Elegant and floral. Rose-tinted world.",
    war: "Gritty and chaotic. Muted greys, browns, and smoke-filled skies.",
    sunset: "Emotional and transient. Warm oranges, pinks, and purples of early evening.",
    cold: "Icy and frozen. Brilliant whites and chilling blues.",
    violet: "Mystical and enchanting. Various shades of purple.",
    nature: "Primal and organic. Vibrant greens and earth tones.",
    artdeco: "Vintage 1920s style. Geometric patterns and bold high-contrast colors.",
    intrigue: "Political tension or espionage. Deep blues and cool greys with sharp lighting.",
    wasteland: "Post-apocalyptic. Dust browns, rust reds, and desolation.",
    patriotic: "Nationalistic or military pride. Red, white, and blue accents.",
    cyan: "Underwater or high-tech energy. Bright cyan and deep teal.",
    silver: "Divine or futuristic elegance. Clean whites and metallic silvers.",
    obsidian: "The void or deep space. Deep blacks and pitch-dark surfaces.",
    gothic: "Victorian horror or dark romance. Black lace, velvet, and deep crimsons.",
    academy: "Scholarly and academic. Dark wood, parchment, and library vibes.",
    apocalypse: "Destruction and fire. Flaming oranges and ashen greys.",
    steampunk: "Industrial revolution meets fantasy. Copper, brass, and steam-filled workshop colors.",
    liminal: "Eerie transitional spaces. Flat lighting, minimalist, and surreal.",
    foundation: "Clinical and sterile. Bright fluorescent lights and containment facility greys.",
    abyssal: "Deep oceanic depths. Pitch black water with bioluminescent accents.",
  },
  ambience: {
    cave: "Deep cavern sounds. Dripping water, wind whistling through tunnels, and distant echoes.",
    city: "Urban background. Distant chatter, vehicle hums, and the general bustle of a crowd.",
    combat: "Stakes are high. Clashing of blades, explosions, and intense drums.",
    desert: "Desolate wind. Chilled at night, scorching heat during the day. Sand whistling.",
    dungeon: "Subterranean prison or ruin. Clanking chains, heavy doors, and a damp, low hum.",
    forest: "Nature's chorus. Chirping birds, rustling leaves, and a sense of life.",
    horror: "Unsettling silence. Creaking wood, distant screams, and discordant strings.",
    market: "Loud and lively. Street vendors shouting, bargaining, and various shop sounds.",
    mystical: "Magical hum. Ethereal bells, floating melodies, and otherworldly chimes.",
    ocean: "The sound of waves. Crashing surf, seagulls, and the rhythmic pulse of the sea.",
    quiet: "Peaceful silence. Soft ambient air, no immediate distractions. Good for reading or thinking.",
    rain: "Pitter-patter of rain. Relaxing or depressing depending on context.",
    scifi: "Technological hums. Computer bleeps, sliding doors, and the whir of electronics.",
    snow: "Muted silence. The soft crunch of snow underfoot and muffled winds.",
    storm: "Violent weather. Cracking thunder, howling wind, and torrential downpour.",
    tavern: "Cozy social setting. Laughter, clinking glasses, and a crackling fireplace.",
    mountain: "High altitude winds. Thin air, distant rockfalls, and epic openness.",
    swamp: "Murky bubbling. Crickets, frogs, and the squelch of mud.",
    village: "Rural peace. Farm animals, blacksmith's hammer, and soft country air.",
    temple: "Reverent chanting. Incense smoke, booming gongs, and deep meditation bells.",
    castle: "Drafty stone halls. Echoing footsteps, heavy tapestries, and ceremonial fanfares.",
    ruins: "The sound of history. Crumbling stone, persistent wind, and total desolation.",
    underwater: "Muffled and heavy. Bubbles, currents, and the deep booming of the abyss.",
    space: "The true void. A subtle low-frequency radiation hum and the absolute lack of air.",
  },
  weather: {
    none: "Standard weather for the environment; no special precipitation or effects.",
    rain: "Liquid precipitation. From light drizzle to heavy downpours.",
    snow: "Frozen precipitation. From light flurries to blizzards.",
    fog: "Thick mist reducing visibility. Good for mystery or horror.",
    embers: "Floating sparks or burning debris. Use for scenes of fire or magic.",
    flicker: "Unstable lighting. Good for horror, faulty tech, or flickering torches.",
    sunny: "Bright, direct sunlight with high visibility.",
    clear: "Clear night sky or crisp day without clouds.",
    partly_cloudy: "Scattered clouds with intermittent sun.",
    cloudy: "Overcast sky, diffused lighting.",
    overcast: "Thick gray sky, somber mood.",
    drizzle: "Very light, fine rain.",
    heavy_rain: "Torrential downpour with reduced visibility.",
    thunderstorm: "Rain with lightning and thunder.",
    light_snow: "Gentle snowfall.",
    heavy_snow: "Dense snowfall.",
    blizzard: "Extreme snow with high winds and zero visibility.",
    mist: "Light fog, often found near water.",
    haze: "Reduced visibility due to dust or smoke.",
    windy: "Strong gusts of air affecting movement and sound.",
    gale: "Very strong winds, potentially dangerous.",
    dust_storm: "Visibility reduced by blowing dust/sand.",
    sandstorm: "Intense blowing sand in desert environments.",
  },
};
