import { ThemeConfig } from "@/types";

/**
 * Default state colors for dark mode
 * These provide consistent semantic coloring across themes
 */
const DEFAULT_STATE_VARS = {
  // Success - Green tones
  "--theme-success": "#22c55e",
  "--theme-success-muted": "#166534",
  // Warning - Yellow/Amber tones (used for unlocked indicators)
  "--theme-warning": "#eab308",
  "--theme-warning-muted": "#a16207",
  // Error - Red tones
  "--theme-error": "#ef4444",
  "--theme-error-muted": "#991b1b",
  // Info - Blue tones
  "--theme-info": "#3b82f6",
  "--theme-info-muted": "#1d4ed8",
  // Unlocked - Gold/Yellow (for revealed hidden content)
  "--theme-unlocked": "#fbbf24",
  "--theme-unlocked-muted": "#b45309",
  // Secret - Purple tones (for secret outcomes, hidden objectives)
  "--theme-secret": "#a855f7",
  "--theme-secret-muted": "#7e22ce",
  // Danger - Rose/Red tones (for true descriptions, hidden truths)
  "--theme-danger": "#fb7185",
  "--theme-danger-muted": "#be123c",
};

/**
 * Default state colors for light/day mode
 */
const DEFAULT_DAY_STATE_VARS = {
  // Success - Green tones (darker for light backgrounds)
  "--theme-success": "#16a34a",
  "--theme-success-muted": "#22c55e",
  // Warning - Yellow/Amber tones
  "--theme-warning": "#ca8a04",
  "--theme-warning-muted": "#eab308",
  // Error - Red tones
  "--theme-error": "#dc2626",
  "--theme-error-muted": "#ef4444",
  // Info - Blue tones
  "--theme-info": "#2563eb",
  "--theme-info-muted": "#3b82f6",
  // Unlocked - Gold/Yellow
  "--theme-unlocked": "#d97706",
  "--theme-unlocked-muted": "#f59e0b",
  // Secret - Purple tones
  "--theme-secret": "#9333ea",
  "--theme-secret-muted": "#a855f7",
  // Danger - Rose/Red tones
  "--theme-danger": "#e11d48",
  "--theme-danger-muted": "#fb7185",
};

export const ENV_THEMES: Record<string, ThemeConfig> = {
  // Standard Fantasy / Mystic
  fantasy: {
    vars: {
      "--theme-bg": "#020617",
      "--theme-surface": "#0f172a",
      "--theme-surface-highlight": "#1e293b",
      "--theme-border": "#334155",
      "--theme-primary": "#f59e0b",
      "--theme-primary-hover": "#d97706",
      "--theme-text": "#e2e8f0",
      "--theme-muted": "#94a3b8",
      ...DEFAULT_STATE_VARS,
    },
    dayVars: {
      "--theme-bg": "#f8fafc",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#f1f5f9",
      "--theme-border": "#cbd5e1",
      "--theme-primary": "#d97706",
      "--theme-primary-hover": "#b45309",
      "--theme-text": "#0f172a",
      "--theme-muted": "#64748b",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-fantasy",
  },
  // Sci-Fi / Tech
  scifi: {
    vars: {
      "--theme-bg": "#000000",
      "--theme-surface": "#09090b",
      "--theme-surface-highlight": "#18181b",
      "--theme-border": "#27272a",
      "--theme-primary": "#06b6d4",
      "--theme-primary-hover": "#0891b2",
      "--theme-text": "#e4e4e7",
      "--theme-muted": "#a1a1aa",
      ...DEFAULT_STATE_VARS,
      "--theme-info": "#22d3ee",
      "--theme-info-muted": "#0891b2",
    },
    dayVars: {
      "--theme-bg": "#f0f9ff",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e0f2fe",
      "--theme-border": "#bae6fd",
      "--theme-primary": "#0891b2",
      "--theme-primary-hover": "#0e7490",
      "--theme-text": "#0c4a6e",
      "--theme-muted": "#0369a1",
      ...DEFAULT_DAY_STATE_VARS,
      "--theme-info": "#0891b2",
      "--theme-info-muted": "#22d3ee",
    },
    fontClass: "font-scifi",
  },
  // Cyberpunk / Neon
  cyberpunk: {
    vars: {
      "--theme-bg": "#1a0b2e",
      "--theme-surface": "#2e1065",
      "--theme-surface-highlight": "#4c1d95",
      "--theme-border": "#701a75",
      "--theme-primary": "#d946ef",
      "--theme-primary-hover": "#c026d3",
      "--theme-text": "#fdf4ff",
      "--theme-muted": "#e879f9",
      ...DEFAULT_STATE_VARS,
      "--theme-success": "#4ade80",
      "--theme-warning": "#facc15",
      "--theme-secret": "#e879f9",
      "--theme-secret-muted": "#c026d3",
    },
    dayVars: {
      "--theme-bg": "#fdf4ff",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#fae8ff",
      "--theme-border": "#f0abfc",
      "--theme-primary": "#c026d3",
      "--theme-primary-hover": "#a21caf",
      "--theme-text": "#4a044e",
      "--theme-muted": "#86198f",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-cyberpunk",
  },
  // Horror / Dark
  horror: {
    vars: {
      "--theme-bg": "#1c1917",
      "--theme-surface": "#292524",
      "--theme-surface-highlight": "#44403c",
      "--theme-border": "#7f1d1d",
      "--theme-primary": "#ef4444",
      "--theme-primary-hover": "#dc2626",
      "--theme-text": "#e7e5e4",
      "--theme-muted": "#a8a29e",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#ef4444",
      "--theme-danger-muted": "#7f1d1d",
      "--theme-unlocked": "#fcd34d",
      "--theme-secret": "#c084fc",
    },
    dayVars: {
      "--theme-bg": "#fff1f2",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#ffe4e6",
      "--theme-border": "#fecdd3",
      "--theme-primary": "#dc2626",
      "--theme-primary-hover": "#b91c1c",
      "--theme-text": "#450a0a",
      "--theme-muted": "#9f1239",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-horror",
  },
  // Mystery / Noir
  mystery: {
    vars: {
      "--theme-bg": "#0a0a0a",
      "--theme-surface": "#171717",
      "--theme-surface-highlight": "#262626",
      "--theme-border": "#404040",
      "--theme-primary": "#fbbf24",
      "--theme-primary-hover": "#f59e0b",
      "--theme-text": "#d4d4d4",
      "--theme-muted": "#737373",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#fcd34d",
      "--theme-unlocked-muted": "#ca8a04",
    },
    dayVars: {
      "--theme-bg": "#fafafa",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#f5f5f5",
      "--theme-border": "#d4d4d4",
      "--theme-primary": "#d97706",
      "--theme-primary-hover": "#b45309",
      "--theme-text": "#171717",
      "--theme-muted": "#525252",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Romance / Pink
  romance: {
    vars: {
      "--theme-bg": "#1a1018",
      "--theme-surface": "#291521",
      "--theme-surface-highlight": "#451e30",
      "--theme-border": "#831843",
      "--theme-primary": "#f472b6",
      "--theme-primary-hover": "#ec4899",
      "--theme-text": "#fce7f3",
      "--theme-muted": "#db2777",
      ...DEFAULT_STATE_VARS,
      "--theme-success": "#86efac",
      "--theme-secret": "#f0abfc",
      "--theme-secret-muted": "#d946ef",
    },
    dayVars: {
      "--theme-bg": "#fff1f2",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#ffe4e6",
      "--theme-border": "#fbcfe8",
      "--theme-primary": "#db2777",
      "--theme-primary-hover": "#be185d",
      "--theme-text": "#831843",
      "--theme-muted": "#9d174d",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-sans",
  },
  // Palace / Royal
  royal: {
    vars: {
      "--theme-bg": "#220505",
      "--theme-surface": "#450a0a",
      "--theme-surface-highlight": "#600f0f",
      "--theme-border": "#b45309",
      "--theme-primary": "#fbbf24",
      "--theme-primary-hover": "#d97706",
      "--theme-text": "#fffbeb",
      "--theme-muted": "#92400e",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#fcd34d",
      "--theme-unlocked-muted": "#d97706",
    },
    dayVars: {
      "--theme-bg": "#fffbeb",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#fef3c7",
      "--theme-border": "#fde68a",
      "--theme-primary": "#d97706",
      "--theme-primary-hover": "#b45309",
      "--theme-text": "#451a03",
      "--theme-muted": "#92400e",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-fantasy",
  },
  // Wuxia / Ink
  wuxia: {
    vars: {
      "--theme-bg": "#1c1c1c",
      "--theme-surface": "#2a2a2a",
      "--theme-surface-highlight": "#3d3d3d",
      "--theme-border": "#525252",
      "--theme-primary": "#ef4444",
      "--theme-primary-hover": "#b91c1c",
      "--theme-text": "#f5f5f4",
      "--theme-muted": "#a8a29e",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#ef4444",
      "--theme-danger-muted": "#991b1b",
    },
    dayVars: {
      "--theme-bg": "#f5f5f4",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e7e5e4",
      "--theme-border": "#d6d3d1",
      "--theme-primary": "#b91c1c",
      "--theme-primary-hover": "#991b1b",
      "--theme-text": "#1c1917",
      "--theme-muted": "#57534e",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Demonic / Dark Red
  demonic: {
    vars: {
      "--theme-bg": "#0f0505",
      "--theme-surface": "#1a0a0a",
      "--theme-surface-highlight": "#2b1111",
      "--theme-border": "#7f1d1d",
      "--theme-primary": "#ef4444",
      "--theme-primary-hover": "#dc2626",
      "--theme-text": "#fef2f2",
      "--theme-muted": "#991b1b",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#f87171",
      "--theme-danger-muted": "#991b1b",
      "--theme-secret": "#c084fc",
    },
    dayVars: {
      "--theme-bg": "#fef2f2",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#fee2e2",
      "--theme-border": "#fecaca",
      "--theme-primary": "#dc2626",
      "--theme-primary-hover": "#b91c1c",
      "--theme-text": "#450a0a",
      "--theme-muted": "#991b1b",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Xianxia / Ethereal Blue
  ethereal: {
    vars: {
      "--theme-bg": "#0f1c2e",
      "--theme-surface": "#1e293b",
      "--theme-surface-highlight": "#334155",
      "--theme-border": "#64748b",
      "--theme-primary": "#38bdf8",
      "--theme-primary-hover": "#0284c7",
      "--theme-text": "#f0f9ff",
      "--theme-muted": "#94a3b8",
      ...DEFAULT_STATE_VARS,
      "--theme-info": "#7dd3fc",
      "--theme-info-muted": "#0284c7",
    },
    dayVars: {
      "--theme-bg": "#f0f9ff",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e0f2fe",
      "--theme-border": "#bae6fd",
      "--theme-primary": "#0284c7",
      "--theme-primary-hover": "#0369a1",
      "--theme-text": "#0c4a6e",
      "--theme-muted": "#075985",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // CEO / Modern Dark
  modern: {
    vars: {
      "--theme-bg": "#111827",
      "--theme-surface": "#1f2937",
      "--theme-surface-highlight": "#374151",
      "--theme-border": "#4b5563",
      "--theme-primary": "#6366f1",
      "--theme-primary-hover": "#4f46e5",
      "--theme-text": "#f9fafb",
      "--theme-muted": "#9ca3af",
      ...DEFAULT_STATE_VARS,
      "--theme-info": "#818cf8",
      "--theme-info-muted": "#4f46e5",
    },
    dayVars: {
      "--theme-bg": "#f9fafb",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#f3f4f6",
      "--theme-border": "#d1d5db",
      "--theme-primary": "#4f46e5",
      "--theme-primary-hover": "#4338ca",
      "--theme-text": "#111827",
      "--theme-muted": "#6b7280",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-sans",
  },
  // Gold / Opulent
  gold: {
    vars: {
      "--theme-bg": "#000000",
      "--theme-surface": "#1a1a1a",
      "--theme-surface-highlight": "#333333",
      "--theme-border": "#ffd700",
      "--theme-primary": "#ffd700",
      "--theme-primary-hover": "#e6c200",
      "--theme-text": "#ffffff",
      "--theme-muted": "#bfbfbf",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#ffd700",
      "--theme-unlocked-muted": "#b8860b",
      "--theme-warning": "#ffd700",
    },
    dayVars: {
      "--theme-bg": "#ffffff",
      "--theme-surface": "#fefce8",
      "--theme-surface-highlight": "#fef9c3",
      "--theme-border": "#eab308",
      "--theme-primary": "#eab308",
      "--theme-primary-hover": "#ca8a04",
      "--theme-text": "#000000",
      "--theme-muted": "#854d0e",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Villain / Purple
  villain: {
    vars: {
      "--theme-bg": "#0f0505",
      "--theme-surface": "#2b0b0b",
      "--theme-surface-highlight": "#4a1414",
      "--theme-border": "#7f1d1d",
      "--theme-primary": "#9333ea",
      "--theme-primary-hover": "#7e22ce",
      "--theme-text": "#f3e8ff",
      "--theme-muted": "#a855f7",
      ...DEFAULT_STATE_VARS,
      "--theme-secret": "#c084fc",
      "--theme-secret-muted": "#9333ea",
    },
    dayVars: {
      "--theme-bg": "#faf5ff",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#f3e8ff",
      "--theme-border": "#d8b4fe",
      "--theme-primary": "#9333ea",
      "--theme-primary-hover": "#7e22ce",
      "--theme-text": "#3b0764",
      "--theme-muted": "#7e22ce",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-fantasy",
  },
  // Period / Sepia
  sepia: {
    vars: {
      "--theme-bg": "#2c241b",
      "--theme-surface": "#433629",
      "--theme-surface-highlight": "#5c4d3c",
      "--theme-border": "#a18e72",
      "--theme-primary": "#d4c4a8",
      "--theme-primary-hover": "#e3d5bc",
      "--theme-text": "#f5f0e6",
      "--theme-muted": "#a89f91",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#d4a574",
      "--theme-unlocked-muted": "#a67c52",
    },
    dayVars: {
      "--theme-bg": "#f5f5f4",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e7e5e4",
      "--theme-border": "#d6d3d1",
      "--theme-primary": "#a18e72",
      "--theme-primary-hover": "#8c7b62",
      "--theme-text": "#292524",
      "--theme-muted": "#78716c",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Female Growth / Rose
  rose: {
    vars: {
      "--theme-bg": "#1a0505",
      "--theme-surface": "#2b0a0a",
      "--theme-surface-highlight": "#4a1212",
      "--theme-border": "#9f1239",
      "--theme-primary": "#fb7185",
      "--theme-primary-hover": "#f43f5e",
      "--theme-text": "#fff1f2",
      "--theme-muted": "#fda4af",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#fb7185",
      "--theme-danger-muted": "#e11d48",
    },
    dayVars: {
      "--theme-bg": "#fff1f2",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#ffe4e6",
      "--theme-border": "#fda4af",
      "--theme-primary": "#e11d48",
      "--theme-primary-hover": "#be123c",
      "--theme-text": "#881337",
      "--theme-muted": "#be123c",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // War / Blood
  war: {
    vars: {
      "--theme-bg": "#0a0a0a",
      "--theme-surface": "#171717",
      "--theme-surface-highlight": "#262626",
      "--theme-border": "#b91c1c",
      "--theme-primary": "#ef4444",
      "--theme-primary-hover": "#dc2626",
      "--theme-text": "#f5f5f5",
      "--theme-muted": "#737373",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#ef4444",
      "--theme-danger-muted": "#b91c1c",
      "--theme-error": "#dc2626",
    },
    dayVars: {
      "--theme-bg": "#fef2f2",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#fee2e2",
      "--theme-border": "#fca5a5",
      "--theme-primary": "#ef4444",
      "--theme-primary-hover": "#dc2626",
      "--theme-text": "#450a0a",
      "--theme-muted": "#991b1b",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-fantasy",
  },
  // Ancient Romance / Orange
  sunset: {
    vars: {
      "--theme-bg": "#1c1917",
      "--theme-surface": "#292524",
      "--theme-surface-highlight": "#44403c",
      "--theme-border": "#d6d3d1",
      "--theme-primary": "#fdba74",
      "--theme-primary-hover": "#fb923c",
      "--theme-text": "#fafaf9",
      "--theme-muted": "#a8a29e",
      ...DEFAULT_STATE_VARS,
      "--theme-warning": "#fb923c",
      "--theme-warning-muted": "#ea580c",
    },
    dayVars: {
      "--theme-bg": "#fff7ed",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#ffedd5",
      "--theme-border": "#fed7aa",
      "--theme-primary": "#f97316",
      "--theme-primary-hover": "#ea580c",
      "--theme-text": "#431407",
      "--theme-muted": "#9a3412",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Angst / Cold Blue
  cold: {
    vars: {
      "--theme-bg": "#0f172a",
      "--theme-surface": "#1e293b",
      "--theme-surface-highlight": "#334155",
      "--theme-border": "#94a3b8",
      "--theme-primary": "#38bdf8",
      "--theme-primary-hover": "#0ea5e9",
      "--theme-text": "#f1f5f9",
      "--theme-muted": "#64748b",
      ...DEFAULT_STATE_VARS,
      "--theme-info": "#7dd3fc",
      "--theme-info-muted": "#0284c7",
    },
    dayVars: {
      "--theme-bg": "#f0f9ff",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e0f2fe",
      "--theme-border": "#7dd3fc",
      "--theme-primary": "#0ea5e9",
      "--theme-primary-hover": "#0284c7",
      "--theme-text": "#0c4a6e",
      "--theme-muted": "#0369a1",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Reunion / Violet
  violet: {
    vars: {
      "--theme-bg": "#18181b",
      "--theme-surface": "#27272a",
      "--theme-surface-highlight": "#3f3f46",
      "--theme-border": "#a1a1aa",
      "--theme-primary": "#a78bfa",
      "--theme-primary-hover": "#8b5cf6",
      "--theme-text": "#f4f4f5",
      "--theme-muted": "#71717a",
      ...DEFAULT_STATE_VARS,
      "--theme-secret": "#c4b5fd",
      "--theme-secret-muted": "#8b5cf6",
    },
    dayVars: {
      "--theme-bg": "#f5f3ff",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#ede9fe",
      "--theme-border": "#c4b5fd",
      "--theme-primary": "#8b5cf6",
      "--theme-primary-hover": "#7c3aed",
      "--theme-text": "#4c1d95",
      "--theme-muted": "#6d28d9",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Farming / Green
  nature: {
    vars: {
      "--theme-bg": "#14281d",
      "--theme-surface": "#1d3b2a",
      "--theme-surface-highlight": "#2d5740",
      "--theme-border": "#4ade80",
      "--theme-primary": "#86efac",
      "--theme-primary-hover": "#4ade80",
      "--theme-text": "#f0fdf4",
      "--theme-muted": "#86efac",
      ...DEFAULT_STATE_VARS,
      "--theme-success": "#4ade80",
      "--theme-success-muted": "#22c55e",
    },
    dayVars: {
      "--theme-bg": "#f0fdf4",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#dcfce7",
      "--theme-border": "#86efac",
      "--theme-primary": "#22c55e",
      "--theme-primary-hover": "#16a34a",
      "--theme-text": "#14532d",
      "--theme-muted": "#15803d",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-sans",
  },
  // Republican / Art Deco
  artdeco: {
    vars: {
      "--theme-bg": "#1a1614",
      "--theme-surface": "#2b2420",
      "--theme-surface-highlight": "#423832",
      "--theme-border": "#d4af37",
      "--theme-primary": "#14b8a6",
      "--theme-primary-hover": "#0d9488",
      "--theme-text": "#f5f5f4",
      "--theme-muted": "#a8a29e",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#d4af37",
      "--theme-unlocked-muted": "#a67c52",
    },
    dayVars: {
      "--theme-bg": "#f5f5f4",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e7e5e4",
      "--theme-border": "#d4af37",
      "--theme-primary": "#0d9488",
      "--theme-primary-hover": "#0f766e",
      "--theme-text": "#292524",
      "--theme-muted": "#57534e",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Intrigue / Blood Red
  intrigue: {
    vars: {
      "--theme-bg": "#190808",
      "--theme-surface": "#360f0f",
      "--theme-surface-highlight": "#591c1c",
      "--theme-border": "#7f1d1d",
      "--theme-primary": "#f87171",
      "--theme-primary-hover": "#ef4444",
      "--theme-text": "#fef2f2",
      "--theme-muted": "#fca5a5",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#f87171",
      "--theme-danger-muted": "#b91c1c",
    },
    dayVars: {
      "--theme-bg": "#fef2f2",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#fee2e2",
      "--theme-border": "#fca5a5",
      "--theme-primary": "#ef4444",
      "--theme-primary-hover": "#dc2626",
      "--theme-text": "#450a0a",
      "--theme-muted": "#991b1b",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Survival / Rust
  wasteland: {
    vars: {
      "--theme-bg": "#1a120b",
      "--theme-surface": "#2e1f12",
      "--theme-surface-highlight": "#4a321d",
      "--theme-border": "#ea580c",
      "--theme-primary": "#f97316",
      "--theme-primary-hover": "#ea580c",
      "--theme-text": "#fff7ed",
      "--theme-muted": "#fdba74",
      ...DEFAULT_STATE_VARS,
      "--theme-warning": "#f97316",
      "--theme-warning-muted": "#c2410c",
    },
    dayVars: {
      "--theme-bg": "#fff7ed",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#ffedd5",
      "--theme-border": "#fdba74",
      "--theme-primary": "#ea580c",
      "--theme-primary-hover": "#c2410c",
      "--theme-text": "#431407",
      "--theme-muted": "#9a3412",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-scifi",
  },
  // Patriotism / Blue Gold
  patriotic: {
    vars: {
      "--theme-bg": "#1e1b4b",
      "--theme-surface": "#312e81",
      "--theme-surface-highlight": "#4338ca",
      "--theme-border": "#ef4444",
      "--theme-primary": "#fbbf24",
      "--theme-primary-hover": "#f59e0b",
      "--theme-text": "#eef2ff",
      "--theme-muted": "#a5b4fc",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#fbbf24",
      "--theme-error": "#ef4444",
    },
    dayVars: {
      "--theme-bg": "#eef2ff",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e0e7ff",
      "--theme-border": "#ef4444",
      "--theme-primary": "#d97706",
      "--theme-primary-hover": "#b45309",
      "--theme-text": "#1e1b4b",
      "--theme-muted": "#4338ca",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Son in Law / Cyan
  cyan: {
    vars: {
      "--theme-bg": "#111827",
      "--theme-surface": "#1f2937",
      "--theme-surface-highlight": "#374151",
      "--theme-border": "#6b7280",
      "--theme-primary": "#22d3ee",
      "--theme-primary-hover": "#06b6d4",
      "--theme-text": "#f9fafb",
      "--theme-muted": "#9ca3af",
      ...DEFAULT_STATE_VARS,
      "--theme-info": "#22d3ee",
      "--theme-info-muted": "#0891b2",
    },
    dayVars: {
      "--theme-bg": "#f9fafb",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#f3f4f6",
      "--theme-border": "#9ca3af",
      "--theme-primary": "#06b6d4",
      "--theme-primary-hover": "#0891b2",
      "--theme-text": "#111827",
      "--theme-muted": "#4b5563",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-sans",
  },
  // White Moonlight / Silver
  silver: {
    vars: {
      "--theme-bg": "#0f172a",
      "--theme-surface": "#1e293b",
      "--theme-surface-highlight": "#334155",
      "--theme-border": "#94a3b8",
      "--theme-primary": "#e2e8f0",
      "--theme-primary-hover": "#cbd5e1",
      "--theme-text": "#f8fafc",
      "--theme-muted": "#94a3b8",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#e2e8f0",
      "--theme-unlocked-muted": "#94a3b8",
    },
    dayVars: {
      "--theme-bg": "#f8fafc",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#f1f5f9",
      "--theme-border": "#cbd5e1",
      "--theme-primary": "#64748b",
      "--theme-primary-hover": "#475569",
      "--theme-text": "#0f172a",
      "--theme-muted": "#64748b",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Yandere / Blood Red
  obsessive: {
    vars: {
      "--theme-bg": "#000000",
      "--theme-surface": "#1a0505",
      "--theme-surface-highlight": "#330a0a",
      "--theme-border": "#ff0000",
      "--theme-primary": "#ff0000",
      "--theme-primary-hover": "#cc0000",
      "--theme-text": "#ffe4e6",
      "--theme-muted": "#fda4af",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#ff0000",
      "--theme-danger-muted": "#cc0000",
      "--theme-error": "#ff0000",
    },
    dayVars: {
      "--theme-bg": "#fff1f2",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#ffe4e6",
      "--theme-border": "#ff0000",
      "--theme-primary": "#dc2626",
      "--theme-primary-hover": "#b91c1c",
      "--theme-text": "#450a0a",
      "--theme-muted": "#991b1b",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-horror",
  },
  // CS Student / Emerald
  emerald: {
    vars: {
      "--theme-bg": "#022c22",
      "--theme-surface": "#064e3b",
      "--theme-surface-highlight": "#065f46",
      "--theme-border": "#059669",
      "--theme-primary": "#34d399",
      "--theme-primary-hover": "#10b981",
      "--theme-text": "#ecfdf5",
      "--theme-muted": "#6ee7b7",
      ...DEFAULT_STATE_VARS,
      "--theme-success": "#34d399",
      "--theme-success-muted": "#059669",
    },
    dayVars: {
      "--theme-bg": "#ecfdf5",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#d1fae5",
      "--theme-border": "#34d399",
      "--theme-primary": "#059669",
      "--theme-primary-hover": "#047857",
      "--theme-text": "#064e3b",
      "--theme-muted": "#10b981",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-sans",
  },
  // Infinite Flow / Danger
  danger: {
    vars: {
      "--theme-bg": "#09090b",
      "--theme-surface": "#18181b",
      "--theme-surface-highlight": "#27272a",
      "--theme-border": "#3f3f46",
      "--theme-primary": "#f43f5e",
      "--theme-primary-hover": "#e11d48",
      "--theme-text": "#e4e4e7",
      "--theme-muted": "#a1a1aa",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#f43f5e",
      "--theme-danger-muted": "#be123c",
    },
    dayVars: {
      "--theme-bg": "#f4f4f5",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e4e4e7",
      "--theme-border": "#d4d4d8",
      "--theme-primary": "#e11d48",
      "--theme-primary-hover": "#be123c",
      "--theme-text": "#18181b",
      "--theme-muted": "#71717a",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-scifi",
  },
  // Entertainment / Glamour
  glamour: {
    vars: {
      "--theme-bg": "#1a1018",
      "--theme-surface": "#291521",
      "--theme-surface-highlight": "#451e30",
      "--theme-border": "#f472b6",
      "--theme-primary": "#fbbf24",
      "--theme-primary-hover": "#f59e0b",
      "--theme-text": "#fdf2f8",
      "--theme-muted": "#fbcfe8",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#fbbf24",
      "--theme-secret": "#f0abfc",
    },
    dayVars: {
      "--theme-bg": "#fdf2f8",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#fce7f3",
      "--theme-border": "#f472b6",
      "--theme-primary": "#d97706",
      "--theme-primary-hover": "#b45309",
      "--theme-text": "#831843",
      "--theme-muted": "#db2777",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-sans",
  },
  // Esports / RGB
  rgb: {
    vars: {
      "--theme-bg": "#020617",
      "--theme-surface": "#0f172a",
      "--theme-surface-highlight": "#1e293b",
      "--theme-border": "#3b82f6",
      "--theme-primary": "#22c55e",
      "--theme-primary-hover": "#16a34a",
      "--theme-text": "#f8fafc",
      "--theme-muted": "#94a3b8",
      ...DEFAULT_STATE_VARS,
      "--theme-success": "#22c55e",
      "--theme-info": "#3b82f6",
      "--theme-error": "#ef4444",
    },
    dayVars: {
      "--theme-bg": "#f8fafc",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#f1f5f9",
      "--theme-border": "#3b82f6",
      "--theme-primary": "#16a34a",
      "--theme-primary-hover": "#15803d",
      "--theme-text": "#0f172a",
      "--theme-muted": "#64748b",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-sans",
  },
  // Rough Guy / Stone
  stone: {
    vars: {
      "--theme-bg": "#1c1917",
      "--theme-surface": "#292524",
      "--theme-surface-highlight": "#44403c",
      "--theme-border": "#78716c",
      "--theme-primary": "#d97706",
      "--theme-primary-hover": "#b45309",
      "--theme-text": "#f5f5f4",
      "--theme-muted": "#a8a29e",
      ...DEFAULT_STATE_VARS,
      "--theme-warning": "#d97706",
      "--theme-warning-muted": "#92400e",
    },
    dayVars: {
      "--theme-bg": "#f5f5f4",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e7e5e4",
      "--theme-border": "#a8a29e",
      "--theme-primary": "#b45309",
      "--theme-primary-hover": "#92400e",
      "--theme-text": "#1c1917",
      "--theme-muted": "#78716c",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-sans",
  },
  // Wife Chasing / Heartbreak
  heartbreak: {
    vars: {
      "--theme-bg": "#0f172a",
      "--theme-surface": "#1e293b",
      "--theme-surface-highlight": "#334155",
      "--theme-border": "#94a3b8",
      "--theme-primary": "#f43f5e",
      "--theme-primary-hover": "#e11d48",
      "--theme-text": "#f1f5f9",
      "--theme-muted": "#64748b",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#f43f5e",
      "--theme-danger-muted": "#be123c",
    },
    dayVars: {
      "--theme-bg": "#f1f5f9",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e2e8f0",
      "--theme-border": "#f43f5e",
      "--theme-primary": "#e11d48",
      "--theme-primary-hover": "#be123c",
      "--theme-text": "#0f172a",
      "--theme-muted": "#64748b",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-sans",
  },
  // Interstellar / Cosmic
  interstellar: {
    vars: {
      "--theme-bg": "#0b0d17",
      "--theme-surface": "#15192b",
      "--theme-surface-highlight": "#20253e",
      "--theme-border": "#4338ca",
      "--theme-primary": "#818cf8",
      "--theme-primary-hover": "#6366f1",
      "--theme-text": "#e0e7ff",
      "--theme-muted": "#6366f1",
      ...DEFAULT_STATE_VARS,
      "--theme-info": "#a5b4fc",
      "--theme-info-muted": "#6366f1",
      "--theme-secret": "#c4b5fd",
    },
    dayVars: {
      "--theme-bg": "#e0e7ff",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#c7d2fe",
      "--theme-border": "#818cf8",
      "--theme-primary": "#4f46e5",
      "--theme-primary-hover": "#4338ca",
      "--theme-text": "#1e1b4b",
      "--theme-muted": "#4338ca",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-scifi",
  },
  // Gothic / Dark Gold
  gothic: {
    vars: {
      "--theme-bg": "#0c0a09",
      "--theme-surface": "#1c1917",
      "--theme-surface-highlight": "#292524",
      "--theme-border": "#78716c",
      "--theme-primary": "#d4af37",
      "--theme-primary-hover": "#b45309",
      "--theme-text": "#e7e5e4",
      "--theme-muted": "#a8a29e",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#d4af37",
      "--theme-unlocked-muted": "#a67c52",
    },
    dayVars: {
      "--theme-bg": "#f5f5f4",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e7e5e4",
      "--theme-border": "#a8a29e",
      "--theme-primary": "#b45309",
      "--theme-primary-hover": "#92400e",
      "--theme-text": "#1c1917",
      "--theme-muted": "#78716c",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Academy / Navy Gold
  academy: {
    vars: {
      "--theme-bg": "#172554",
      "--theme-surface": "#1e3a8a",
      "--theme-surface-highlight": "#1e40af",
      "--theme-border": "#fbbf24",
      "--theme-primary": "#fbbf24",
      "--theme-primary-hover": "#f59e0b",
      "--theme-text": "#eff6ff",
      "--theme-muted": "#93c5fd",
      ...DEFAULT_STATE_VARS,
      "--theme-unlocked": "#fbbf24",
      "--theme-unlocked-muted": "#d97706",
      "--theme-info": "#93c5fd",
    },
    dayVars: {
      "--theme-bg": "#eff6ff",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#dbeafe",
      "--theme-border": "#fbbf24",
      "--theme-primary": "#d97706",
      "--theme-primary-hover": "#b45309",
      "--theme-text": "#172554",
      "--theme-muted": "#2563eb",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-serif",
  },
  // Apocalypse / Rust Grey
  apocalypse: {
    vars: {
      "--theme-bg": "#262626",
      "--theme-surface": "#404040",
      "--theme-surface-highlight": "#525252",
      "--theme-border": "#ef4444",
      "--theme-primary": "#ef4444",
      "--theme-primary-hover": "#dc2626",
      "--theme-text": "#d4d4d4",
      "--theme-muted": "#a3a3a3",
      ...DEFAULT_STATE_VARS,
      "--theme-danger": "#ef4444",
      "--theme-danger-muted": "#b91c1c",
      "--theme-warning": "#f97316",
    },
    dayVars: {
      "--theme-bg": "#f5f5f5",
      "--theme-surface": "#ffffff",
      "--theme-surface-highlight": "#e5e5e5",
      "--theme-border": "#ef4444",
      "--theme-primary": "#dc2626",
      "--theme-primary-hover": "#b91c1c",
      "--theme-text": "#171717",
      "--theme-muted": "#525252",
      ...DEFAULT_DAY_STATE_VARS,
    },
    fontClass: "font-scifi",
  },
};
