import { StoryThemeConfig } from "../../types";

// Visual/Atmospheric Themes (Dynamic)
export const CATEGORY_KEYS = [
  "all",
  "ancient",
  "modern",
  "fantasy",
  "suspense",
  "wuxia",
  "scifi",
  "game",
  "novel",
  "movie",
  "chinese_short_drama",
] as const;
export type CategoryKey = (typeof CATEGORY_KEYS)[number];

// Story Themes (Static Genres)
export const THEMES: Record<string, StoryThemeConfig> = {
  time_travel: {
    envTheme: "ethereal",
    defaultAtmosphere: { envTheme: "ethereal", ambience: "mystical" },
    icon: "⏳",
    categories: ["ancient", "chinese_short_drama"],
  },
  wuxia: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "⚔️",
    categories: ["ancient"],
  },
  palace_drama: {
    envTheme: "royal",
    defaultAtmosphere: { envTheme: "royal", ambience: "market" },
    icon: "👑",
    categories: ["ancient", "chinese_short_drama"],
  },
  ancient_romance: {
    envTheme: "sunset",
    defaultAtmosphere: { envTheme: "sunset", ambience: "desert" },
    icon: "💖",
    categories: ["ancient", "chinese_short_drama"],
  },
  republican: {
    envTheme: "artdeco",
    defaultAtmosphere: { envTheme: "artdeco", ambience: "city" },
    icon: "🎩",
    categories: ["ancient", "chinese_short_drama"],
  },
  demonic_cultivation: {
    envTheme: "demonic",
    defaultAtmosphere: { envTheme: "demonic", ambience: "cave" },
    icon: "😈",
    categories: ["ancient"],
  },
  period_drama: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "tavern" },
    icon: "🎭",
    categories: ["ancient"],
  },
  intrigue: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "🤫",
    categories: ["ancient"],
  },
  xianxia: {
    envTheme: "ethereal",
    defaultAtmosphere: { envTheme: "ethereal", ambience: "mystical" },
    icon: "✨",
    categories: ["ancient"],
  },
  rough_guy: {
    envTheme: "wasteland",
    defaultAtmosphere: { envTheme: "wasteland", ambience: "cave" },
    icon: "👊",
    categories: ["modern"],
  },
  prison: {
    envTheme: "wasteland",
    defaultAtmosphere: { envTheme: "wasteland", ambience: "storm" },
    icon: "⛓️",
    categories: ["modern", "suspense", "chinese_short_drama"],
  },
  misplaced_marriage: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "rain" },
    icon: "💍",
    categories: ["modern", "chinese_short_drama"],
  },
  face_slapping: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "👋",
    categories: ["modern", "chinese_short_drama"],
  },
  artist_compound: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "quiet" },
    icon: "🎨",
    categories: ["modern", "chinese_short_drama"],
  },
  professor_simulator: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🎓",
    categories: ["modern", "game"],
  },
  ww2: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "💣",
    categories: ["modern"],
  },
  ww1: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🪖",
    categories: ["modern"],
  },
  esports: {
    envTheme: "cyberpunk",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "🎮",
    categories: ["modern"],
  },
  ceo: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "💼",
    categories: ["modern", "chinese_short_drama"],
  },
  modern_romance: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "quiet" },
    icon: "❤️",
    categories: ["modern"],
  },
  villain_alliance: {
    envTheme: "villain",
    defaultAtmosphere: { envTheme: "villain", ambience: "storm" },
    icon: "😈",
    categories: ["modern", "chinese_short_drama"],
  },
  wealthy_family: {
    envTheme: "gold",
    defaultAtmosphere: { envTheme: "gold", ambience: "market" },
    icon: "💰",
    categories: ["modern", "suspense", "chinese_short_drama"],
  },
  stepmother_warmth: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "👩‍👧‍👦",
    categories: ["modern", "chinese_short_drama"],
  },
  patriotism: {
    envTheme: "patriotic",
    defaultAtmosphere: { envTheme: "patriotic", ambience: "combat" },
    icon: "🇨🇳",
    categories: ["modern"],
  },
  family_ethics: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "tavern" },
    icon: "🏠",
    categories: ["modern", "chinese_short_drama"],
  },
  treasure_appraisal: {
    envTheme: "gold",
    defaultAtmosphere: { envTheme: "gold", ambience: "market" },
    icon: "🔍",
    categories: ["modern", "chinese_short_drama"],
  },
  chinese_civil_war: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🚩",
    categories: ["modern"],
  },
  business_queen_90s: {
    envTheme: "gold",
    defaultAtmosphere: { envTheme: "gold", ambience: "city" },
    icon: "👠",
    categories: ["modern", "chinese_short_drama"],
  },
  anti_japanese_war: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🇨🇳",
    categories: ["modern"],
  },
  divorce: {
    envTheme: "cold",
    defaultAtmosphere: { envTheme: "cold", ambience: "rain" },
    icon: "💔",
    categories: ["modern", "chinese_short_drama"],
  },
  body_swap: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "👯",
    categories: ["modern", "chinese_short_drama"],
  },
  cs_grad_journey: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "🎓",
    categories: ["modern"],
  },
  hidden_identity: {
    envTheme: "mystery",
    defaultAtmosphere: { envTheme: "mystery", ambience: "rain" },
    icon: "🕶️",
    categories: ["modern", "suspense", "chinese_short_drama"],
  },
  genius_baby: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "👶",
    categories: ["modern", "chinese_short_drama"],
  },
  cute_pet: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "🐾",
    categories: ["modern", "fantasy", "chinese_short_drama"],
  },
  era_80s: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "market" },
    icon: "📻",
    categories: ["modern", "chinese_short_drama"],
  },
  cannon_fodder_counterattack: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "💥",
    categories: ["modern", "chinese_short_drama"],
  },
  reunion: {
    envTheme: "violet",
    defaultAtmosphere: { envTheme: "violet", ambience: "mystical" },
    icon: "🤝",
    categories: ["modern", "chinese_short_drama"],
  },
  professional_romance: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "quiet" },
    icon: "👩‍⚕️",
    categories: ["modern", "chinese_short_drama"],
  },
  wild_youth: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🎸",
    categories: ["modern"],
  },
  cs_student: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "💻",
    categories: ["modern"],
  },
  flash_marriage: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "quiet" },
    icon: "⚡",
    categories: ["modern", "chinese_short_drama"],
  },
  shen_hao: {
    envTheme: "gold",
    defaultAtmosphere: { envTheme: "gold", ambience: "city" },
    icon: "💳",
    categories: ["modern", "chinese_short_drama"],
  },
  divine_doctor: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "💊",
    categories: ["modern", "fantasy", "chinese_short_drama"],
  },
  mutual_redemption: {
    envTheme: "violet",
    defaultAtmosphere: { envTheme: "violet", ambience: "mystical" },
    icon: "💞",
    categories: ["modern", "chinese_short_drama"],
  },
  secret_agent_wife: {
    envTheme: "cyberpunk",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "🕶️",
    categories: ["modern", "chinese_short_drama"],
  },
  special_forces: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🎖️",
    categories: ["modern", "chinese_short_drama"],
  },
  white_moonlight: {
    envTheme: "silver",
    defaultAtmosphere: { envTheme: "silver", ambience: "scifi" },
    icon: "🌕",
    categories: ["modern", "chinese_short_drama"],
  },
  sweet_pet: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "quiet" },
    icon: "🍬",
    categories: ["modern", "chinese_short_drama"],
  },
  same_sex_love: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "quiet" },
    icon: "🏳️‍🌈",
    categories: ["modern", "suspense"],
  },
  superhero_villain: {
    envTheme: "villain",
    defaultAtmosphere: { envTheme: "villain", ambience: "city" },
    icon: "🦹",
    categories: ["modern", "suspense"],
  },
  system_stream: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "🤖",
    categories: ["modern", "fantasy", "chinese_short_drama"],
  },
  love_after_marriage: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "quiet" },
    icon: "💍",
    categories: ["modern", "chinese_short_drama"],
  },
  rural: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "🚜",
    categories: ["modern", "chinese_short_drama"],
  },
  metaphysics: {
    envTheme: "mystery",
    defaultAtmosphere: { envTheme: "mystery", ambience: "mystical" },
    icon: "☯️",
    categories: ["modern", "chinese_short_drama"],
  },
  industry_elite: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🏢",
    categories: ["modern", "chinese_short_drama"],
  },
  entertainment: {
    envTheme: "gold",
    defaultAtmosphere: { envTheme: "gold", ambience: "city" },
    icon: "🎬",
    categories: ["modern", "chinese_short_drama"],
  },
  god_of_war: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "⚔️",
    categories: ["modern", "chinese_short_drama"],
  },
  true_false_heiress: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "👭",
    categories: ["modern", "chinese_short_drama"],
  },
  rebirth_revenge: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "🩸",
    categories: ["modern", "suspense", "chinese_short_drama"],
  },
  rebirth_redemption: {
    envTheme: "violet",
    defaultAtmosphere: { envTheme: "violet", ambience: "mystical" },
    icon: "🔄",
    categories: ["modern", "chinese_short_drama"],
  },
  wife_chasing: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "rain" },
    icon: "🏃‍♀️",
    categories: ["modern", "chinese_short_drama"],
  },
  son_in_law: {
    envTheme: "cyan",
    defaultAtmosphere: { envTheme: "cyan", ambience: "ocean" },
    icon: "👨‍👩‍👧",
    categories: ["modern", "chinese_short_drama"],
  },
  cyberpunk: {
    envTheme: "cyberpunk",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "🌃",
    categories: ["fantasy"],
  },
  infinite_flow: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "♾️",
    categories: ["fantasy"],
  },
  fantasy: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "quiet" },
    icon: "🐉",
    categories: ["fantasy"],
  },
  scifi: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "🚀",
    categories: ["fantasy"],
  },
  farming: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "🌾",
    categories: ["fantasy"],
  },
  mystery: {
    envTheme: "mystery",
    defaultAtmosphere: { envTheme: "mystery", ambience: "rain" },
    icon: "🔍",
    categories: ["suspense"],
  },
  yandere: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "horror" },
    icon: "🔪",
    categories: ["suspense", "chinese_short_drama"],
  },
  female_growth: {
    envTheme: "rose",
    defaultAtmosphere: { envTheme: "rose", ambience: "quiet" },
    icon: "🌸",
    categories: ["suspense"],
  },
  espionage: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "rain" },
    icon: "🕵️",
    categories: ["suspense"],
  },
  villain_op: {
    envTheme: "villain",
    defaultAtmosphere: { envTheme: "villain", ambience: "horror" },
    icon: "🦹",
    categories: ["suspense"],
  },
  angst: {
    envTheme: "cold",
    defaultAtmosphere: { envTheme: "cold", ambience: "snow" },
    icon: "💔",
    categories: ["suspense", "chinese_short_drama"],
  },
  horror: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "horror" },
    icon: "👻",
    categories: ["suspense"],
  },
  long_aotian: {
    envTheme: "gold",
    defaultAtmosphere: { envTheme: "gold", ambience: "market" },
    icon: "💪",
    categories: ["suspense", "chinese_short_drama"],
  },
  survival: {
    envTheme: "wasteland",
    defaultAtmosphere: { envTheme: "wasteland", ambience: "desert" },
    icon: "🏕️",
    categories: ["suspense"],
  },
  return_strong: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🔥",
    categories: ["suspense", "chinese_short_drama"],
  },
  zombie: {
    envTheme: "wasteland",
    defaultAtmosphere: { envTheme: "wasteland", ambience: "storm" },
    icon: "🧟",
    categories: ["suspense"],
  },
  war_god: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🛡️",
    categories: ["suspense", "chinese_short_drama"],
  },
  historical_general: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "combat" },
    icon: "🏮",
    categories: ["chinese_short_drama", "historical"],
  },
  bestie_brother: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "quiet" },
    icon: "👫",
    categories: ["chinese_short_drama", "romance"],
  },
  guardian_bond: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "storm" },
    icon: "🚨",
    categories: ["chinese_short_drama", "bl"],
  },
  supreme_commander_bl: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "city" },
    icon: "🦅",
    categories: ["chinese_short_drama", "bl"],
  },
  cang_yuan_tu: {
    envTheme: "ethereal",
    defaultAtmosphere: { envTheme: "ethereal", ambience: "mystical" },
    icon: "⚡",
    categories: ["ancient", "fantasy", "novel"],
    restricted: true,
  },
  ancient_scholar: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "quiet" },
    icon: "🖌️",
    categories: ["ancient", "novel"],
    restricted: true,
  },
  ming_dynasty_exam: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "quiet" },
    icon: "📚",
    categories: ["ancient", "novel"],
    restricted: true,
  },
  romance_of_tiger_and_rose: {
    envTheme: "sunset",
    defaultAtmosphere: { envTheme: "sunset", ambience: "city" },
    icon: "🌹",
    categories: ["ancient", "fantasy", "novel"],
    restricted: true,
  },
  assassins_creed: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "city" },
    icon: "🦅",
    categories: ["ancient", "game"],
    restricted: true,
  },
  da_feng_da_geng_ren: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "city" },
    icon: "🥁",
    categories: ["ancient", "suspense", "novel"],
    restricted: true,
  },
  imperial_preceptor: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "👑",
    categories: ["ancient", "novel"],
    restricted: true,
  },
  black_sails: {
    envTheme: "cyan",
    defaultAtmosphere: { envTheme: "cyan", ambience: "ocean" },
    icon: "🏴‍☠️",
    categories: ["ancient", "movie"],
    restricted: true,
  },
  black_myth_wukong: {
    envTheme: "demonic",
    defaultAtmosphere: { envTheme: "demonic", ambience: "mystical" },
    icon: "🐵",
    categories: ["ancient", "fantasy", "game"],
    restricted: true,
  },
  golden_terrace: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "🏯",
    categories: ["ancient", "novel"],
    restricted: true,
  },
  jin_yan: {
    envTheme: "artdeco",
    defaultAtmosphere: { envTheme: "artdeco", ambience: "city" },
    icon: "🎙️",
    categories: ["ancient", "novel"],
    restricted: true,
  },
  rome: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "city" },
    icon: "🏛️",
    categories: ["ancient", "movie"],
    restricted: true,
  },
  quan_huan: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "📜",
    categories: ["ancient", "novel"],
    restricted: true,
  },
  spartacus: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "⚔️",
    categories: ["ancient", "movie"],
    restricted: true,
  },
  zhen_huan_zhuan: {
    envTheme: "royal",
    defaultAtmosphere: { envTheme: "royal", ambience: "city" },
    icon: "🌺",
    categories: ["ancient", "novel"],
    restricted: true,
  },
  zhui_xu: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "market" },
    icon: "🏮",
    categories: ["ancient", "suspense", "novel"],
    restricted: true,
  },
  an_zhi_wo_yi: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "💼",
    categories: ["modern", "novel"],
    restricted: true,
  },
  farewell_my_concubine: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "city" },
    icon: "🎭",
    categories: ["modern", "movie"],
    restricted: true,
  },
  batman: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "🦇",
    categories: ["modern", "suspense", "movie"],
    restricted: true,
  },
  batman_villain: {
    envTheme: "villain",
    defaultAtmosphere: { envTheme: "villain", ambience: "city" },
    icon: "🦇",
    categories: ["modern", "suspense", "movie"],
    restricted: true,
  },
  dont_talk_to_me: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🤐",
    categories: ["modern", "novel"],
    restricted: true,
  },
  school_hunk_ex: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🎓",
    categories: ["modern", "novel"],
    restricted: true,
  },
  my_unique_hero: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "city" },
    icon: "🦸‍♂️",
    categories: ["modern", "movie"],
    restricted: true,
  },
  the_boys: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🦸",
    categories: ["modern", "suspense", "movie"],
    restricted: true,
  },
  godfather: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "🌹",
    categories: ["modern", "suspense", "movie"],
    restricted: true,
  },
  gone_with_the_wind: {
    envTheme: "sunset",
    defaultAtmosphere: { envTheme: "sunset", ambience: "quiet" },
    icon: "👒",
    categories: ["modern", "movie"],
    restricted: true,
  },
  the_chirping_birds_do_not_fly: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "🐦",
    categories: ["modern", "suspense", "movie"],
    restricted: true,
  },
  cardcaptor_sakura: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "quiet" },
    icon: "🌸",
    categories: ["modern", "fantasy"],
    restricted: true,
  },
  mou_mou: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "quiet" },
    icon: "🌳",
    categories: ["modern", "novel"],
    restricted: true,
  },
  qi_xi_zhi_lu: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "quiet" },
    icon: "🏝️",
    categories: ["modern", "novel"],
    restricted: true,
  },
  qiu_yi_wei_qi: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🍂",
    categories: ["modern", "novel"],
    restricted: true,
  },
  l4d: {
    envTheme: "wasteland",
    defaultAtmosphere: { envTheme: "wasteland", ambience: "storm" },
    icon: "🧟",
    categories: ["modern", "game"],
    restricted: true,
  },
  ninja_gaiden: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "🥷",
    categories: ["modern", "game"],
    restricted: true,
  },
  delta_force: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🔫",
    categories: ["modern", "game"],
    restricted: true,
  },
  link_click: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "📷",
    categories: ["modern", "fantasy", "suspense"],
    restricted: true,
  },
  sekaiichi_hatsukoi: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "city" },
    icon: "📚",
    categories: ["modern", "movie"],
    restricted: true,
  },
  sui_yu_tou_zhu: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "quiet" },
    icon: "💎",
    categories: ["modern", "novel"],
    restricted: true,
  },
  titanic: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "ocean" },
    icon: "🚢",
    categories: ["modern", "movie"],
    restricted: true,
  },
  ti_deng_kan_ci_dao: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🔪",
    categories: ["modern", "novel"],
    restricted: true,
  },
  turing_code: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "💻",
    categories: ["modern", "suspense"],
    restricted: true,
  },
  fake_slackers: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🏫",
    categories: ["modern", "novel"],
    restricted: true,
  },
  generation_war: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🎖️",
    categories: ["modern", "movie"],
    restricted: true,
  },
  i_was_threatened_by_the_man_i_most_wanted_to_hug: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "city" },
    icon: "🫂",
    categories: ["modern", "movie"],
    restricted: true,
  },
  shawshank_redemption: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "quiet" },
    icon: "🔨",
    categories: ["modern", "movie"],
    restricted: true,
  },
  schindlers_list: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "quiet" },
    icon: "🕯️",
    categories: ["modern", "movie"],
    restricted: true,
  },
  yu_zui: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "👮",
    categories: ["modern", "suspense", "novel"],
    restricted: true,
  },
  slay_gods_hospital: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🏥",
    categories: ["modern", "fantasy", "novel"],
    restricted: true,
  },
  expedition_33: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🧭",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  elden_ring: {
    envTheme: "gold",
    defaultAtmosphere: { envTheme: "gold", ambience: "market" },
    icon: "💍",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  alice_in_wonderland: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🐇",
    categories: ["fantasy", "movie"],
    restricted: true,
  },
  balala_fairies: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "mystical" },
    icon: "🧚‍♀️",
    categories: ["fantasy", "movie"],
    restricted: true,
  },
  pokemon: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "⚡",
    categories: ["fantasy", "game", "movie"],
    restricted: true,
  },
  game_of_thrones: {
    envTheme: "demonic",
    defaultAtmosphere: { envTheme: "demonic", ambience: "horror" },
    icon: "🐉",
    categories: ["fantasy", "movie"],
    restricted: true,
  },
  disney_twisted_wonderland: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "city" },
    icon: "🪞",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  soul_land: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "quiet" },
    icon: "🌾",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  monster_hunter: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🦖",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  lord_of_the_mysteries: {
    envTheme: "mystery",
    defaultAtmosphere: { envTheme: "mystery", ambience: "city" },
    icon: "🧐",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  harry_potter: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "quiet" },
    icon: "🪄",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  spongebob: {
    envTheme: "cyan",
    defaultAtmosphere: { envTheme: "cyan", ambience: "ocean" },
    icon: "🧽",
    categories: ["fantasy", "movie"],
    restricted: true,
  },
  dark_souls: {
    envTheme: "demonic",
    defaultAtmosphere: { envTheme: "demonic", ambience: "horror" },
    icon: "🔥",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  naruto: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "forest" },
    icon: "🍥",
    categories: ["fantasy", "game", "movie"],
    restricted: true,
  },
  the_titans_bride: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "💍",
    categories: ["fantasy", "movie"],
    restricted: true,
  },
  dnd: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🎲",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  dragon_raja: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "city" },
    icon: "🐉",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  wow: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "⚔️",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  shepherd_of_gods: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🐮",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  spirited_away: {
    envTheme: "ethereal",
    defaultAtmosphere: { envTheme: "ethereal", ambience: "mystical" },
    icon: "🏮",
    categories: ["fantasy", "movie"],
    restricted: true,
  },
  elder_scrolls: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "📜",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  my_assassin_status: {
    envTheme: "intrigue",
    defaultAtmosphere: { envTheme: "intrigue", ambience: "city" },
    icon: "🗡️",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  saint_seiya: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "mystical" },
    icon: "⭐",
    categories: ["fantasy", "movie"],
    restricted: true,
  },
  digimon_1: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🦖",
    categories: ["fantasy", "game", "movie"],
    restricted: true,
  },
  digimon_3: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "city" },
    icon: "🃏",
    categories: ["fantasy", "game", "movie"],
    restricted: true,
  },
  digimon_4: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🔥",
    categories: ["fantasy", "game", "movie"],
    restricted: true,
  },
  digimon_5: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "city" },
    icon: "🥊",
    categories: ["fantasy", "game", "movie"],
    restricted: true,
  },
  terraria: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "🌳",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  let_this_grieving_soul_retire: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "😩",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  copper_coins: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "mystical" },
    icon: "🪙",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  minecraft: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "⛏️",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  witcher: {
    envTheme: "demonic",
    defaultAtmosphere: { envTheme: "demonic", ambience: "horror" },
    icon: "🐺",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  bloodborne: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "horror" },
    icon: "🩸",
    categories: ["fantasy", "suspense", "game"],
    restricted: true,
  },
  wild_last_boss: {
    envTheme: "demonic",
    defaultAtmosphere: { envTheme: "demonic", ambience: "horror" },
    icon: "🦅",
    categories: ["fantasy", "game", "novel"],
    restricted: true,
  },
  lol: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🏆",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  yu_gi_oh: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🃏",
    categories: ["fantasy", "game", "movie"],
    restricted: true,
  },
  frieren: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🧝‍♀️",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  may_i_ask_one_final_thing: {
    envTheme: "royal",
    defaultAtmosphere: { envTheme: "royal", ambience: "market" },
    icon: "👊",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  battle_through_heavens: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "🔥",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  mortals_journey: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "💊",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  desolate_era: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "⚔️",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  mo_dao_zu_shi: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "🪈",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  thousand_autumns: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "🍂",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  scum_villain: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "🥒",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  first_buddha_cultivator: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "mystical" },
    icon: "🙏",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  tian_guan_ci_fu: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "🦋",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  peerless: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "⚔️",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  xian_ni: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "⚡",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  yi_jian_shuang_han: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "tavern" },
    icon: "🗡️",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  avatar: {
    envTheme: "nature",
    defaultAtmosphere: { envTheme: "nature", ambience: "forest" },
    icon: "👽",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  superman: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "city" },
    icon: "🦸‍♂️",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  superman_villain: {
    envTheme: "villain",
    defaultAtmosphere: { envTheme: "villain", ambience: "city" },
    icon: "🦸‍♂️",
    categories: ["scifi", "suspense", "movie"],
    restricted: true,
  },
  inception: {
    envTheme: "mystery",
    defaultAtmosphere: { envTheme: "mystery", ambience: "city" },
    icon: "🌀",
    categories: ["scifi", "suspense", "movie"],
    restricted: true,
  },
  ultraman_tiga: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "city" },
    icon: "✨",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  detroit_become_human: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "🤖",
    categories: ["scifi", "game"],
    restricted: true,
  },
  doraemon: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🐱",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  avengers: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "city" },
    icon: "🅰️",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  avengers_villain: {
    envTheme: "villain",
    defaultAtmosphere: { envTheme: "villain", ambience: "city" },
    icon: "🅰️",
    categories: ["scifi", "suspense", "movie"],
    restricted: true,
  },
  the_matrix: {
    envTheme: "cyberpunk",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "💊",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  kamen_rider: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🏍️",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  ultraman_geed: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "city" },
    icon: "🧬",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  helldivers: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🫡",
    categories: ["scifi", "game"],
    restricted: true,
  },
  armor_hero: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "city" },
    icon: "🛡️",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  stellaris: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "🌌",
    categories: ["scifi", "game"],
    restricted: true,
  },
  cyberpunk_2077: {
    envTheme: "cyberpunk",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "🦾",
    categories: ["scifi", "game"],
    restricted: true,
  },
  deus_ex: {
    envTheme: "cyberpunk",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "🕶️",
    categories: ["scifi", "game"],
    restricted: true,
  },
  dead_space: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "👽",
    categories: ["scifi", "game"],
    restricted: true,
  },
  swallowed_star: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "🌌",
    categories: ["scifi", "novel"],
    restricted: true,
  },
  interstellar: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "🚀",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  warframe: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "🥷",
    categories: ["scifi", "game"],
    restricted: true,
  },
  infinite_sequence: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "♾️",
    categories: ["scifi", "suspense", "novel"],
    restricted: true,
  },
  warhammer_40k: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "💀",
    categories: ["scifi", "game"],
    restricted: true,
  },
  spiderman: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🕷️",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  spiderman_villain: {
    envTheme: "villain",
    defaultAtmosphere: { envTheme: "villain", ambience: "city" },
    icon: "🕷️",
    categories: ["scifi", "suspense", "movie"],
    restricted: true,
  },
  mass_effect: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "🌌",
    categories: ["scifi", "game"],
    restricted: true,
  },
  silent_hill: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "horror" },
    icon: "🌫️",
    categories: ["suspense", "game", "movie"],
    restricted: true,
  },
  witness_for_prosecution: {
    envTheme: "sepia",
    defaultAtmosphere: { envTheme: "sepia", ambience: "city" },
    icon: "⚖️",
    categories: ["suspense", "movie"],
    restricted: true,
  },
  resident_evil: {
    envTheme: "wasteland",
    defaultAtmosphere: { envTheme: "wasteland", ambience: "storm" },
    icon: "🧬",
    categories: ["suspense", "game", "movie"],
    restricted: true,
  },
  pennywise: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "horror" },
    icon: "🎈",
    categories: ["suspense", "movie"],
    restricted: true,
  },
  the_conjuring: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "horror" },
    icon: "👻",
    categories: ["suspense", "movie"],
    restricted: true,
  },
  bu_si_zhe: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "city" },
    icon: "🧟",
    categories: ["novel"],
    restricted: true,
  },
  bu_zhun_ying_xiang_wo_xue_xi: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "📚",
    categories: ["novel"],
    restricted: true,
  },
  can_ci_pin: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "🤖",
    categories: ["novel"],
    restricted: true,
  },
  chen_zhou: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🚣",
    categories: ["novel"],
    restricted: true,
  },
  chuan_cheng_zuo_jing: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "💅",
    categories: ["novel"],
    restricted: true,
  },
  da_ge: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🏙️",
    categories: ["novel"],
    restricted: true,
  },
  da_wang_rao_ming: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🙏",
    categories: ["novel"],
    restricted: true,
  },
  dang_ge_fa_shi_nao_ge_ming: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "city" },
    icon: "🔥",
    categories: ["novel"],
    restricted: true,
  },
  dao_mu_bi_ji: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "cave" },
    icon: "⚰️",
    categories: ["novel"],
    restricted: true,
  },
  di_ao_xian_sheng: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🤵",
    categories: ["novel"],
    restricted: true,
  },
  fan_pai_shi_zun: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "mystical" },
    icon: "🌸",
    categories: ["novel"],
    restricted: true,
  },
  gui_chui_deng: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "cave" },
    icon: "🕯️",
    categories: ["novel"],
    restricted: true,
  },
  gui_mie_zhi_ren: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "snow" },
    icon: "👹",
    categories: ["novel"],
    restricted: true,
  },
  guo_men: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🏫",
    categories: ["novel"],
    restricted: true,
  },
  huang_ye_zhi_chun: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "forest" },
    icon: "🍃",
    categories: ["novel"],
    restricted: true,
  },
  jia_gei_bao_jun: {
    envTheme: "royal",
    defaultAtmosphere: { envTheme: "royal", ambience: "city" },
    icon: "👑",
    categories: ["novel"],
    restricted: true,
  },
  jiang_jin_jiu: {
    envTheme: "royal",
    defaultAtmosphere: { envTheme: "royal", ambience: "city" },
    icon: "🍷",
    categories: ["novel"],
    restricted: true,
  },
  jin_pai_zhu_li: {
    envTheme: "gold",
    defaultAtmosphere: { envTheme: "gold", ambience: "city" },
    icon: "🌟",
    categories: ["novel"],
    restricted: true,
  },
  jun_qu_da_yuan: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🎖️",
    categories: ["novel"],
    restricted: true,
  },
  kuai_chuan_zhi_da_lian_kuang_mo: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🎭",
    categories: ["novel"],
    restricted: true,
  },
  li_hai_le_wo_de_yuan_shi_ren: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🍖",
    categories: ["novel"],
    restricted: true,
  },
  lie_huo_jiao_chou: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "mystical" },
    icon: "🔥",
    categories: ["novel"],
    restricted: true,
  },
  liu_yao: {
    envTheme: "ethereal",
    defaultAtmosphere: { envTheme: "ethereal", ambience: "mystical" },
    icon: "🍃",
    categories: ["novel"],
    restricted: true,
  },
  luan_shi_tong_lu: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "desert" },
    icon: "🔥",
    categories: ["novel"],
    restricted: true,
  },
  man_chao_wen_wu_dou_neng_ting_dao_wo_de_xin_sheng: {
    envTheme: "royal",
    defaultAtmosphere: { envTheme: "royal", ambience: "city" },
    icon: "👂",
    categories: ["novel"],
    restricted: true,
  },
  mo_du: {
    envTheme: "mystery",
    defaultAtmosphere: { envTheme: "mystery", ambience: "city" },
    icon: "📖",
    categories: ["novel"],
    restricted: true,
  },
  nan_shen_shuo_ta_gang_guan_zhi: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "👬",
    categories: ["novel"],
    restricted: true,
  },
  ni_shi_bu_shi_xi_huan_wo: {
    envTheme: "romance",
    defaultAtmosphere: { envTheme: "romance", ambience: "quiet" },
    icon: "💌",
    categories: ["novel"],
    restricted: true,
  },
  po_yun: {
    envTheme: "mystery",
    defaultAtmosphere: { envTheme: "mystery", ambience: "city" },
    icon: "🚓",
    categories: ["novel"],
    restricted: true,
  },
  qi_ye: {
    envTheme: "royal",
    defaultAtmosphere: { envTheme: "royal", ambience: "quiet" },
    icon: "📜",
    categories: ["novel"],
    restricted: true,
  },
  qiang_zhe_shi_zen_yang_lian_cheng_de: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "💪",
    categories: ["novel"],
    restricted: true,
  },
  qie_wei_you_xi: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🃏",
    categories: ["novel"],
    restricted: true,
  },
  global_university_entrance_exam: {
    envTheme: "war",
    defaultAtmosphere: { envTheme: "war", ambience: "combat" },
    icon: "🎓",
    categories: ["novel"],
    restricted: true,
  },
  quan_qiu_gao_wu: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🥊",
    categories: ["novel"],
    restricted: true,
  },
  quan_zhi_gao_shou: {
    envTheme: "esports",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "🎮",
    categories: ["novel"],
    restricted: true,
  },
  san_ti: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "city" },
    icon: "🛸",
    categories: ["novel"],
    restricted: true,
  },
  sang_bing_da_xue: {
    envTheme: "horror",
    defaultAtmosphere: { envTheme: "horror", ambience: "city" },
    icon: "🧟",
    categories: ["novel"],
    restricted: true,
  },
  sha_po_lang: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "combat" },
    icon: "🐺",
    categories: ["novel"],
    restricted: true,
  },
  shan_he_biao_li: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "mystical" },
    icon: "⛰️",
    categories: ["novel"],
    restricted: true,
  },
  sheng_chong_ju_xing: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🌟",
    categories: ["novel"],
    restricted: true,
  },
  shi_shang_zui_qiang_zhui_xu: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "city" },
    icon: "💰",
    categories: ["novel"],
    restricted: true,
  },
  tai_feng_yan: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🌀",
    categories: ["novel"],
    restricted: true,
  },
  tian_qi_yu_bao: {
    envTheme: "cyberpunk",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "🎻",
    categories: ["novel"],
    restricted: true,
  },
  tian_ya_ke: {
    envTheme: "wuxia",
    defaultAtmosphere: { envTheme: "wuxia", ambience: "combat" },
    icon: "🗡️",
    categories: ["novel"],
    restricted: true,
  },
  tong_zhuo_ni_qing_xing_yi_dian: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🏫",
    categories: ["novel"],
    restricted: true,
  },
  wang_you_zhi_jin_zhan_fa_shi: {
    envTheme: "cyberpunk",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "🧙",
    categories: ["novel"],
    restricted: true,
  },
  xiu_zhen_liao_tian_qun: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "📱",
    categories: ["novel"],
    restricted: true,
  },
  ye_de_ming_ming_shu: {
    envTheme: "cyberpunk",
    defaultAtmosphere: { envTheme: "cyberpunk", ambience: "city" },
    icon: "🌃",
    categories: ["novel"],
    restricted: true,
  },
  yi_ji_lv_shi: {
    envTheme: "scifi",
    defaultAtmosphere: { envTheme: "scifi", ambience: "scifi" },
    icon: "⚖️",
    categories: ["novel"],
    restricted: true,
  },
  ying_di: {
    envTheme: "gold",
    defaultAtmosphere: { envTheme: "gold", ambience: "city" },
    icon: "🎬",
    categories: ["novel"],
    restricted: true,
  },
  yuan_shi_zhan_ji: {
    envTheme: "fantasy",
    defaultAtmosphere: { envTheme: "fantasy", ambience: "forest" },
    icon: "🦕",
    categories: ["novel"],
    restricted: true,
  },
  zhen_hun: {
    envTheme: "mystery",
    defaultAtmosphere: { envTheme: "mystery", ambience: "city" },
    icon: "👻",
    categories: ["novel"],
    restricted: true,
  },
  chong_sheng_zhi_si_shui_liu_nian: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🚲",
    categories: ["novel"],
    restricted: true,
  },
  zhuang_yuan_lang_zong_shi_bu_ji_ge: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🕰️",
    categories: ["novel"],
    restricted: true,
  },
  zhui_wei: {
    envTheme: "modern",
    defaultAtmosphere: { envTheme: "modern", ambience: "city" },
    icon: "🚗",
    categories: ["novel"],
    restricted: true,
  },
};
