/**
 * ============================================================================
 * FIELD RESPONSIBILITY GUIDE
 * ============================================================================
 *
 * SYSTEM-MANAGED FIELDS (auto-generated, AI should NOT set):
 * - id: Auto-generated by system (inv:N, npc:N, loc:N, etc.)
 * - createdAt: Set when entity is created (Date.now())
 * - lastModified: Updated on any modification (Date.now())
 * - lastAccess: Updated when AI queries entity (turn number)
 * - isVisited: Set when player visits location
 * - discoveredAt: Set when location is first discovered
 *
 * AI-CONTROLLED FIELDS (AI decides value):
 * - visible.*: All visible layer content
 * - hidden.*: All hidden layer content (GM knowledge)
 * - unlocked: AI decides when hidden info is revealed (narrative judgment)
 * - known: Whether player knows this entity exists
 * - notes: NPC observations of player behavior
 * - highlight: Set true by AI when entity changes (cleared by UI after render)
 * - aliveEntities: AI marks entities needed for next turn
 *
 * MIXED FIELDS (AI sets initial, system may override):
 * - status: AI updates, but system may have constraints
 * - affinity: AI updates based on story, system validates range (0-100)
 * ============================================================================
 */

// Action Result type for handleAction return value
export interface StateChanges {
  // Detailed changes with names
  itemsAdded?: Array<{ name: string }>;
  itemsRemoved?: Array<{ name: string }>;
  npcsAdded?: Array<{ name: string }>;
  npcsRemoved?: Array<{ name: string }>;
  questsAdded?: Array<{ name: string }>;
  questsCompleted?: Array<{ name: string }>;
  locationsDiscovered?: Array<{ name: string }>;
  skillsGained?: Array<{ name: string }>;
  conditionsChanged?: Array<{ name: string }>;
}

export type ActionResult =
  | { success: true; stateChanges: StateChanges; legacyMessage: string }
  | { success: false; error: string };

// Context Priority System: How many recent/alive entities to include in context
export const RECENT_LIMITS = {
  inventory: 5,
  relationships: 4,
  locations: 3,
  quests: 3,
  knowledge: 4,
  timeline: 5,
} as const;

// Alive Entities: entities marked by AI as needed for next turn
export interface AliveEntities {
  inventory: string[]; // inv:N IDs
  relationships: string[]; // npc:N IDs
  locations: string[]; // loc:N IDs
  quests: string[]; // quest:N IDs
  knowledge: string[]; // know:N IDs
  timeline: string[]; // evt:N IDs
  // Character internal attributes (subset tracking)
  skills: string[]; // Character skill IDs relevant to next turn
  conditions: string[]; // Character condition IDs relevant to next turn
  hiddenTraits: string[]; // Character hidden trait IDs relevant to next turn
  causalChains: string[]; // CausalChain chainIds with pending consequences
}

export interface GameState {
  // Tree Structure: ID -> Segment
  nodes: Record<string, StorySegment>;
  activeNodeId: string | null; // The leaf node of the current path
  rootNodeId: string | null;

  inventory: InventoryItem[];
  relationships: Relationship[];
  quests: Quest[];
  character: CharacterStatus;
  knowledge: KnowledgeEntry[]; // Player's accumulated knowledge about the world
  factions: Faction[]; // Major power groups

  // Location System
  currentLocation: string;
  locations: Location[];

  // UI State (Persisted)
  uiState: UIState;

  // Meta
  outline: StoryOutline | null;
  summaries: StorySummary[]; // Array of summaries, where the last one is the most current
  lastSummarizedIndex: number; // Track how many nodes have been summarized to avoid re-summarizing

  isProcessing: boolean;
  isImageGenerating: boolean;
  generatingNodeId: string | null; // Track specifically which node is generating an image
  error: string | null;
  // Unified Atmosphere (controls visual theme, effects, and audio)
  atmosphere: string; // The current atmosphere (e.g. "forest", "horror", "city")
  theme: string; // Static game genre (e.g. "Cyberpunk", "Wuxia")
  time: string; // In-game time tracking

  // Stats & Logs
  totalTokens: number;
  logs: LogEntry[];

  // Cached Veo Script
  veoScript?: string;

  // Initial Prompt (for retry)
  initialPrompt?: string;

  // New World System Fields
  nextIds: {
    item: number;
    npc: number;
    location: number;
    knowledge: number;
    quest: number;
    faction: number;
    timeline: number;
    causalChain: number;
    skill: number;
    condition: number;
    hiddenTrait: number;
  };
  timeline: TimelineEvent[];
  causalChains: CausalChain[];

  // Context Priority System: entities AI marked as relevant for next turn
  // Cleared at start of each turn, populated by AI via finish_turn
  aliveEntities: AliveEntities;
  // RAG Queries: semantic search queries for next turn context
  // Populated by AI via finish_turn, used at start of next turn
  ragQueries?: string[];
  // Current turn number (incremented on each player action)
  turnNumber: number;

  // Developer Mode Flags
  godMode?: boolean; // God mode: bypass all restrictions and dangers
  unlockMode?: boolean; // Unlock mode: show all hidden info
}

// --- World System Interfaces ---

export interface VisibleInfo {
  description: string;
  appearance?: string;
  notes?: string;
  [key: string]: any;
}

export interface HiddenInfo {
  truth: string;
  realPersonality?: string;
  secrets?: string[];
  realMotives?: string;
  hiddenAttributes?: Record<string, any>;
  [key: string]: any;
}

export interface TimelineEvent {
  id: string;
  gameTime: string;
  category: "player_action" | "npc_action" | "world_event" | "consequence";
  visible: {
    description: string;
    causedBy?: string;
  };
  hidden: {
    trueDescription: string;
    trueCausedBy?: string;
    consequences?: string[];
  };
  involvedEntities?: string[];
  chainId?: string; // Link to a CausalChain
  lastAccess?: number; // Turn number when last accessed/queried by AI
  unlocked?: boolean; // True when true cause/consequences are revealed
  highlight?: boolean; // True when updated in current turn (for UI)
  known?: boolean; // True if the player is aware of this event
}

export interface CausalChain {
  chainId: string;
  rootCause: {
    eventId: string;
    description: string;
  };
  events: TimelineEvent[];
  status: "active" | "resolved" | "interrupted";
  /**
   * PENDING CONSEQUENCES (AI-DECIDED SYSTEM)
   *
   * The AI decides when consequences occur based on:
   * 1. Story context and player actions
   * 2. The 'readyAfterTurn' field (earliest possible trigger)
   * 3. Narrative appropriateness
   *
   * NOTE: 'probability' has been REMOVED. AI makes the decision.
   */
  pendingConsequences?: Array<{
    id: string; // Unique ID for tracking
    description: string; // What could happen
    readyAfterTurn: number; // Turn number AFTER which this consequence CAN trigger (not before)
    createdAtTurn: number; // Turn when this consequence was created
    conditions?: string[]; // Conditions that should be true for trigger (AI evaluates)
    triggered?: boolean; // True once consequence has been triggered
    triggeredAtTurn?: number; // Turn when triggered
    known?: boolean; // True if player witnessed/knows about this consequence
  }>;
}

export interface StorySummary {
  id: number;
  displayText: string; // Concise summary for UI display (visible layer only)
  visible: {
    narrative: string;
    majorEvents: string[];
    characterDevelopment: string;
    worldState: string;
  };
  hidden: {
    truthNarrative: string;
    hiddenPlots: string[];
    npcActions: string[];
    worldTruth: string;
    unrevealed: string[];
  };
  timeRange: {
    from: string;
    to: string;
  };
  nodeRange: {
    fromIndex: number;
    toIndex: number;
  };
}

export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

// Individual tool call record
export interface ToolCallRecord {
  name: string;
  input: Record<string, any>;
  output: any;
  timestamp: number;
}

export interface LogEntry {
  id: string;
  timestamp: number;
  provider: string;
  model: string;
  endpoint: string;
  // For agentic mode: array of tool calls in this turn
  toolCalls?: ToolCallRecord[];
  // Legacy fields for non-agentic mode
  request?: any;
  response?: any;
  usage?: TokenUsage;
}

export interface Faction {
  id: string;
  name: string;
  visible: {
    agenda: string; // Public agenda
    members?: { name: string; title?: string }[]; // Publicly known members
    influence?: string; // Perceived influence description
    relations?: Record<string, string>; // Public alliances/rivalries
  };
  hidden: {
    agenda: string; // Secret agenda
    members?: { name: string; title?: string }[]; // Secret members/leaders
    influence?: string; // True influence description
    relations?: Record<string, string>; // Secret alliances/rivalries
  };
  highlight?: boolean; // True when updated in current turn
  unlocked?: boolean; // True when secret agenda is revealed to player
}

export interface StoryOutline {
  title: string;
  initialTime: string;
  premise: string;
  mainGoal: {
    visible: string; // The apparent main motivation/task
    hidden: string; // The hidden event logic or true nature of the goal
  };
  quests: Quest[]; // Initial quests (replaces mainGoal/goals)
  worldSetting: {
    visible: string;
    hidden: string;
    history: string; // Ancient events that shape the present
  };
  factions: Omit<Faction, "id">[]; // Major power groups
  locations: Omit<Location, "id" | "isVisited" | "createdAt">[]; // Initial locations (Detailed structure)
  character: CharacterStatus; // Initial character state
  inventory?: InventoryItem[]; // Initial inventory
  relationships?: Relationship[]; // Initial relationships
  knowledge?: Omit<KnowledgeEntry, "id">[]; // Initial knowledge
  timeline?: TimelineEvent[]; // Initial timeline events (Backstory)
  // Unified Atmosphere for initial state
  initialAtmosphere: string; // Initial atmosphere (e.g. "forest", "horror", "city")
  // Unlocked flags - set by AI when player discovers hidden info
  worldSettingUnlocked?: boolean; // True when worldSetting.hidden is revealed
  mainGoalUnlocked?: boolean; // True when mainGoal.hidden is revealed
}

export interface SaveSlot {
  id: string;
  name: string;
  timestamp: number;
  theme: string;
  summary: string;
  previewImage?: string;
  // No need to store full state here, just metadata
}

export interface CharacterAttribute {
  label: string;
  value: number;
  maxValue: number;
  color: "red" | "blue" | "green" | "yellow" | "purple" | "gray";
}

export interface CharacterSkill {
  id: string;
  name: string;
  level: string;
  visible: {
    description: string;
    knownEffects: string[];
  };
  hidden: {
    trueDescription: string;
    hiddenEffects: string[];
    drawbacks?: string[];
  };
  category?: string;
  experience?: number;
  unlocked?: boolean; // True when hidden effects are revealed to player
  highlight?: boolean; // True when updated in current turn (for UI)
}

export interface CharacterCondition {
  id: string;
  name: string;
  type: "buff" | "debuff" | "neutral";
  visible: {
    description: string;
    perceivedSeverity: string;
  };
  hidden: {
    trueCause: string;
    actualSeverity: number;
    progression: string;
    cure?: string;
  };
  duration?: number;
  startTime?: number;
  effects: {
    visible: string[];
    hidden: string[];
  };
  unlocked?: boolean; // True when true cause/cure are revealed
  highlight?: boolean; // True when updated in current turn (for UI)
}

export interface HiddenTrait {
  id: string;
  name: string;
  description: string;
  effects: string[];
  triggerConditions?: string[];
  unlocked: boolean; // True when triggerConditions are met and trait is revealed
  highlight?: boolean; // True when updated in current turn (for UI)
}

export interface CharacterStatus {
  name: string;
  title: string;
  status: string;
  attributes: CharacterAttribute[];
  skills: CharacterSkill[];
  conditions: CharacterCondition[];
  hiddenTraits?: HiddenTrait[];
  appearance: string;
  profession?: string;
  background?: string;
  race?: string;
}

export interface ListState {
  pinnedIds: string[];
  customOrder: string[];
}

export interface UIState {
  inventory: ListState;
  locations: ListState;
  relationships: ListState;
  knowledge: ListState; // UI state for knowledge panel
  showSystemFooter?: boolean; // Persisted state for system footer
  sidebarCollapsed?: boolean; // Persisted state for left sidebar collapse
  timelineCollapsed?: boolean; // Persisted state for right timeline collapse
}

export interface Relationship {
  id: string;
  known?: boolean; // Whether the player has met/knows this character
  currentLocation?: string; // NPC's current location ID (e.g., "loc:1"), used to determine if NPC is nearby
  visible: {
    name: string; // The name the player knows them by
    description: string;
    appearance?: string;
    relationshipType: string; // Was status
    currentImpression?: string;
    personality?: string; // Public perception of personality (may differ from hidden truth)
    affinity: number; // Moved from root
    affinityKnown: boolean; // Moved from root
  };
  hidden: {
    trueName?: string; // The character's real name (if different from visible)
    realPersonality: string;
    realMotives: string;
    secrets: string[];
    trueAffinity: number;
    relationshipType: string; // Added
    status: string; // Current state (e.g. "plotting", "injured")
  };
  createdAt: number;
  lastModified: number;
  lastAccess?: number; // Turn number when last accessed/queried by AI
  notes?: string; // NPC's observations of player's displayed knowledge/behavior
  unlocked?: boolean; // True when hidden personality/motives revealed (requires special ability)
  highlight?: boolean; // True when updated in current turn (for UI)
}

export interface StorySegment {
  id: string;
  parentId: string | null; // Pointer to parent for Tree Structure
  text: string;
  choices: string[];
  imagePrompt: string;
  imageUrl?: string;
  audioKey?: string; // Key for cached TTS audio in IndexedDB
  role: "user" | "model";
  timestamp: number;
  summarySnapshot?: StorySummary; // If this node triggered a summary, store it here
  usage?: TokenUsage;

  // Fork-safe Summary State
  summaries?: StorySummary[]; // The total summary of the story up to this point (Dual-layer)
  summarizedIndex?: number; // The index in the history chain where the summary ends

  // Unified Atmosphere System (controls visual theme, effects, and audio)
  atmosphere?: string; // The unified atmosphere (e.g. "forest", "horror", "city")

  narrativeTone?: string; // The tone of the narrative (e.g. "suspenseful", "cheerful")
  imageSkipped?: boolean; // Whether image generation was intentionally skipped by AI
  stateSnapshot?: GameStateSnapshot; // Snapshot of the game state at this point

  // Game Ending
  ending?: EndingType; // If this node is an ending, what type of ending is it?
  forceEnd?: boolean; // If true, game ends permanently (no continue); if false/undefined, player can continue
}

// Game Ending Types
export type EndingType =
  | "death" // Player death / Game Over
  | "victory" // Main goal achieved
  | "true_ending" // Secret/True ending discovered
  | "bad_ending" // Bad outcome but not death
  | "neutral_ending" // Story concluded without clear win/loss
  | null;

export interface GameStateSnapshot {
  // Entity State (Dual-layer)
  inventory: InventoryItem[];
  relationships: Relationship[];
  quests: Quest[];
  character: CharacterStatus;
  knowledge: KnowledgeEntry[];
  locations: Location[];
  currentLocation: string;
  factions: Faction[]; // Added factions to snapshot

  // ID Counters (Critical for forks)
  nextIds: {
    item: number;
    npc: number;
    location: number;
    knowledge: number;
    quest: number;
    faction: number;
    timeline: number;
    causalChain: number;
    skill: number;
    condition: number;
    hiddenTrait: number;
  };

  // World State
  time: string;
  timeline: TimelineEvent[];
  causalChains: CausalChain[];

  // Summaries (Dual-layer)
  summaries: StorySummary[];
  lastSummarizedIndex: number;

  // UI & Meta
  uiState: UIState;
  atmosphere: string; // Unified atmosphere identifier
  veoScript?: string;

  // Context Priority System
  aliveEntities: AliveEntities;
  ragQueries?: string[];
  turnNumber: number;
}

export interface Location {
  id: string;
  name: string;
  visible: {
    description: string;
    knownFeatures: string[];
  };
  hidden: {
    fullDescription: string;
    hiddenFeatures: string[];
    secrets: string[];
  };
  lore?: string;
  isVisited: boolean;
  environment?: string;
  createdAt: number;
  discoveredAt?: number;
  lastAccess?: number; // Turn number when last accessed/queried by AI
  notes?: string;
  unlocked?: boolean; // True when hidden secrets are discovered
  highlight?: boolean; // True when updated in current turn (for UI)
}

export interface KnowledgeEntry {
  id: string;
  title: string;
  category:
    | "landscape"
    | "history"
    | "item"
    | "legend"
    | "faction"
    | "culture"
    | "magic"
    | "technology"
    | "other";
  visible: {
    description: string;
    details?: string;
  };
  hidden: {
    fullTruth: string;
    misconceptions?: string[];
    toBeRevealed?: string[];
  };
  discoveredAt?: string;
  relatedTo?: string[];
  createdAt: number;
  lastModified: number;
  lastAccess?: number; // Turn number when last accessed/queried by AI
  unlocked?: boolean; // True when full truth is revealed
  highlight?: boolean; // True when updated in current turn (for UI)
}

export interface InventoryItem {
  id: string;
  name: string;
  visible: {
    description: string;
    notes?: string;
  };
  hidden: {
    truth: string;
    secrets?: string[];
  };
  createdAt: number;
  lastModified: number;
  lastAccess?: number; // Turn number when last accessed/queried by AI
  lore?: string;
  icon?: string;
  unlocked?: boolean; // True when hidden truth is revealed to player
  highlight?: boolean; // True when updated in current turn (for UI)
}

export interface Quest {
  id: string;
  title: string;
  type: "main" | "side" | "hidden";
  status: "active" | "completed" | "failed";
  visible: {
    description: string;
    objectives: string[];
  };
  hidden: {
    trueDescription?: string;
    trueObjectives?: string[];
    secretOutcome?: string;
  };
  createdAt: number;
  lastModified: number;
  lastAccess?: number; // Turn number when last accessed/queried by AI
  unlocked?: boolean; // True when true objectives/outcome are revealed
  highlight?: boolean; // True when updated in current turn (for UI)
}

export interface InventoryAction {
  action: "add" | "remove" | "update";
  id?: string; // Numeric ID
  name: string; // Name is still useful for reference

  // Dual-layer support
  visible?: {
    description?: string;
    notes?: string;
  };
  hidden?: {
    truth?: string;
    secrets?: string[];
  };

  lore?: string;
  newItem?: string;
  unlocked?: boolean; // Set when hidden truth should be revealed/locked
}

export interface QuestAction {
  action: "add" | "update" | "complete" | "fail";
  id: string;
  title?: string;
  type?: "main" | "side" | "hidden";
  visible?: {
    description?: string;
    objectives?: string[];
  };
  hidden?: {
    trueDescription?: string;
    trueObjectives?: string[];
    secretOutcome?: string;
  };
  unlocked?: boolean; // Set when true objectives should be revealed
}

export interface RelationshipAction {
  action: "add" | "update" | "remove";
  id?: string;
  known?: boolean; // Update known status

  visible?: {
    name?: string; // Update visible name
    description?: string;
    appearance?: string;
    relationshipType?: string;
    currentImpression?: string;
    affinity?: number;
    affinityKnown?: boolean;
  };
  hidden?: {
    realPersonality?: string;
    realMotives?: string;
    secrets?: string[];
    trueAffinity?: number;
    relationshipType?: string;
    status?: string;
  };

  notes?: string;
  unlocked?: boolean; // Set when mind-reading/telepathy reveals hidden personality
}

export interface LocationAction {
  type: "current" | "known";
  action: "update" | "add";
  id?: string;
  name: string;

  visible?: {
    description?: string;
    knownFeatures?: string[];
  };
  hidden?: {
    fullDescription?: string;
    hiddenFeatures?: string[];
    secrets?: string[];
  };

  lore?: string;
  environment?: string;
  notes?: string;
  unlocked?: boolean; // Set when hidden secrets are discovered
}

export interface KnowledgeAction {
  action: "add" | "update";
  id?: string;
  title: string;
  category:
    | "landscape"
    | "history"
    | "item"
    | "legend"
    | "faction"
    | "culture"
    | "magic"
    | "technology"
    | "other";

  visible?: {
    description?: string;
    details?: string;
  };
  hidden?: {
    fullTruth?: string;
    misconceptions?: string[];
    toBeRevealed?: string[];
  };

  discoveredAt?: string;
  relatedTo?: string[];
  unlocked?: boolean; // Set when full truth is revealed
}

export interface CharacterAction {
  target:
    | "attribute"
    | "skill"
    | "status"
    | "appearance"
    | "profession"
    | "background"
    | "race"
    | "condition" // New
    | "hiddenTrait"; // New
  action: "add" | "remove" | "update";
  id?: string; // For skills/conditions
  name: string;

  // For skills/conditions
  visible?: {
    description?: string;
    effects?: string[]; // For conditions
  };
  hidden?: {
    trueDescription?: string;
    hiddenEffects?: string[];
    trueCause?: string; // For conditions
  };

  value?: any;
  intValue?: number;
  strValue?: string;
  maxValue?: number;
  color?: string;
  unlocked?: boolean; // Set when hidden effects should be revealed (skills/conditions)
  // New: Final State from Agentic Loop
  finalState?: GameState;
}

// Note: AdventureTurnInput has been removed. Use GameState directly with TurnContext from aiService.ts

export interface GameResponse {
  narrative: string;
  choices: string[];
  inventoryActions?: InventoryAction[];
  relationshipActions?: RelationshipAction[];
  locationActions?: LocationAction[];
  characterUpdates?: CharacterUpdates;
  questActions?: QuestAction[];
  knowledgeActions?: KnowledgeAction[]; // Player's accumulated knowledge
  imagePrompt?: string;
  // Unified Atmosphere System
  atmosphere?: string; // The unified atmosphere for this segment (e.g. "forest", "horror", "city")
  narrativeTone?: string; // The tone of the narrative
  generateImage?: boolean;
  timeUpdate?: string; // The new time string
  finalState?: GameState; // The full game state after processing
  timelineEvents?: Array<{
    category: "npc_action" | "world_event" | "consequence";
    visible: {
      description: string;
      causedBy?: string;
    };
    hidden: {
      trueDescription: string;
      trueCausedBy?: string;
      consequences?: string[];
    };
    involvedEntities?: string[];
    // Causal Chain Logic
    chainId?: string; // Link to existing chain
    newChain?: {
      description: string; // Description of the chain's theme/cause
    };
    projectedConsequences?: Array<{
      description: string;
      delayTurns: number;
      probability: number;
    }>;
  }>;
  factionActions?: FactionAction[];
  // World Info Updates: track when world-level secrets are unlocked
  worldInfoUpdates?: Array<{
    unlockWorldSetting?: boolean;
    unlockMainGoal?: boolean;
    reason: string;
  }>;
  // Context Priority: entities AI marked as relevant for next turn
  aliveEntities?: AliveEntities;
  // RAG Queries: semantic search queries for next turn context
  ragQueries?: string[];
  // Game Ending: if this response concludes the game
  ending?: EndingType;
  // Force End: if true, game ends permanently (no continue option)
  forceEnd?: boolean;
}

export interface FactionAction {
  action: "update";
  id: string;
  name: string;
  visible?: string;
  hidden?: string;
}

export interface CharacterUpdates {
  attributes?: Array<{
    action: "add" | "update" | "remove";
    name: string;
    value?: number;
    maxValue?: number;
    color?: string;
  }>;
  skills?: Array<{
    action: "add" | "update" | "remove";
    name: string;
    level?: string;
    description?: string;
    unlocked?: boolean; // Set when hidden techniques/true nature revealed
  }>;
  conditions?: Array<{
    action: "add" | "update" | "remove";
    id?: string;
    name: string;
    type?: "buff" | "debuff" | "neutral";
    visible?: {
      description?: string;
      perceivedSeverity?: string;
    };
    hidden?: {
      trueCause?: string;
      actualSeverity?: number;
      progression?: string;
      cure?: string;
    };
    effects?: {
      visible?: string[];
      hidden?: string[];
    };
    unlocked?: boolean; // Set when true diagnosis/cure revealed
  }>;
  hiddenTraits?: Array<{
    action: "add" | "update" | "remove";
    id?: string;
    name: string;
    description?: string;
    effects?: string[];
    triggerConditions?: string[];
    unlocked?: boolean; // Set to true when triggerConditions are met
  }>;
  profile?: {
    status?: string;
    appearance?: string;
    profession?: string;
    background?: string;
    race?: string;
  };
}

export interface ThemeConfig {
  vars: Record<string, string>; // Default (Night)
  dayVars?: Record<string, string>; // Optional Day Mode overrides
  fontClass: string;
}

export interface StoryThemeConfig {
  envTheme: string; // The visual theme key (ENV_THEMES key, e.g. "fantasy", "horror")
  defaultAtmosphere: string; // The default atmosphere (ATMOSPHERES value, e.g. "forest", "cave")
  icon?: string;
  categories?: string[];
  restricted?: boolean;
  backgroundTemplate?: string;
  example?: string;
}

export type LanguageCode = "en" | "zh";

export type AIProvider = "gemini" | "openai" | "openrouter";

export interface ProviderCredentials {
  apiKey?: string;
  baseUrl?: string;
}

export interface FunctionConfig {
  provider: AIProvider;
  modelId: string;
  enabled?: boolean;
  resolution?: string; // e.g. "512x512", "1024x1024"
  thinkingLevel?: "low" | "medium" | "high"; // For Gemini Thinking
  mediaResolution?: "low" | "medium" | "high"; // For Gemini Vision

  gender?: "male" | "female"; // For TTS voice selection (Legacy)
  voice?: string; // Specific voice ID (e.g. "alloy", "coral")
  speed?: number; // 0.25 to 4.0
  format?: "mp3" | "opus" | "aac" | "flac" | "wav" | "pcm";

  // Advanced Model Parameters
  temperature?: number;
  topP?: number;
  topK?: number;
  minP?: number;
}

export interface AISettings {
  gemini: ProviderCredentials;
  openai: ProviderCredentials;
  openrouter: ProviderCredentials;
  contextLen: number; // Max conversation turns before summarization

  story: FunctionConfig;
  lore: FunctionConfig;
  script: FunctionConfig;
  image: FunctionConfig;
  video: FunctionConfig;
  audio: FunctionConfig;
  audioVolume: {
    bgmVolume: number;
    bgmMuted: boolean;
    ttsVolume: number;
    ttsMuted: boolean;
  };
  translation: FunctionConfig;
  language: LanguageCode;

  // Image Generation Settings
  imageTimeout: number; // Timeout in seconds
  manualImageGen: boolean; // Require manual click to generate
  enableFallbackBackground: boolean; // Enable fallback background images

  // Visual Theme Settings
  lockEnvTheme: boolean; // Lock UI theme to story's envTheme, ignoring atmosphere changes

  // RAG Embedding Settings
  embedding: EmbeddingConfig;
}

// ============================================================================
// RAG Embedding System Types
// ============================================================================

export interface EmbeddingConfig extends FunctionConfig {
  enabled: boolean;
  provider: "gemini" | "openai" | "openrouter";
  modelId: string;
  dimensions?: number; // Optional: output dimensions (e.g., 256, 768, 1536)
  chunkSize?: number; // Text chunk size for embedding
  chunkOverlap?: number; // Overlap between chunks
  topK?: number; // Number of results to retrieve
  similarityThreshold?: number; // Minimum similarity score (0-1)
}

export interface EmbeddingDocument {
  id: string; // Unique document ID
  type: "story" | "npc" | "location" | "item" | "knowledge" | "quest" | "event";
  entityId: string; // Reference to the entity (e.g., npc:1, loc:2)
  content: string; // Original text content
  embedding?: Float32Array; // Compressed embedding vector (stored separately)
  metadata?: {
    turnNumber?: number;
    timestamp?: number;
    importance?: number; // 0-1 score for retrieval priority
  };
}

export interface EmbeddingIndex {
  version: number;
  dimensions: number;
  modelId: string;
  documents: EmbeddingDocument[];
  // Embeddings stored as compressed Float32Array chunks
  embeddings?: ArrayBuffer;
}

// ============================================================================
// Save Version Management Types
// ============================================================================

export const CURRENT_SAVE_VERSION = 1;

export interface SaveVersionInfo {
  version: number;
  createdAt: number;
  migratedFrom?: number;
  migrationLog?: string[];
}

export interface VersionedGameState extends GameState {
  _saveVersion: SaveVersionInfo;
  _embeddingIndex?: EmbeddingIndex;
}

export interface ThemeData {
  name: string;
  narrativeStyle: string;
  backgroundTemplate: string;
  example: string;
  worldSetting: string;
}

export interface ModelInfo {
  id: string;
  name?: string;
  capabilities?: {
    image?: boolean;
    video?: boolean;
    audio?: boolean;
    text?: boolean;
    tools?: boolean;
    parallelTools?: boolean;
  };
}

export type FeedLayout = "scroll" | "stack";

export interface ImageGenerationContext {
  theme: string;
  worldSetting?: string; // Added worldSetting
  time?: string;
  location?: {
    name: string;
    environment: string;
    details: string;
  };
  character?: {
    name: string;
    race: string;
    profession: string;
    appearance: string;
    status: string;
  };
  activeNPCs?: {
    name: string;
    description: string;
    appearance: string;
    status: string;
  }[];
}
