import { StoryThemeConfig } from "../../types";

// Visual/Atmospheric Themes (Dynamic)
export const CATEGORY_KEYS = [
  "all",
  "ancient",
  "modern",
  "fantasy",
  "suspense",
  "wuxia",
  "scifi",
  "game",
  "novel",
  "movie",
] as const;
export type CategoryKey = (typeof CATEGORY_KEYS)[number];

// Story Themes (Static Genres)
export const THEMES: Record<string, StoryThemeConfig> = {
  fantasy: {
    envTheme: "fantasy",
    defaultAtmosphere: "quiet",
    icon: "🐉",
    categories: ["fantasy"],
  },
  scifi: {
    envTheme: "scifi",
    defaultAtmosphere: "scifi",
    icon: "🚀",
    categories: ["fantasy"],
  },
  cyberpunk: {
    envTheme: "cyberpunk",
    defaultAtmosphere: "city",
    icon: "🌃",
    categories: ["fantasy"],
  },
  horror: {
    envTheme: "horror",
    defaultAtmosphere: "horror",
    icon: "👻",
    categories: ["suspense"],
  },
  mystery: {
    envTheme: "mystery",
    defaultAtmosphere: "rain",
    icon: "🔍",
    categories: ["suspense"],
  },
  modern_romance: {
    envTheme: "romance",
    defaultAtmosphere: "quiet",
    icon: "❤️",
    categories: ["modern"],
  },
  palace_drama: {
    envTheme: "royal",
    defaultAtmosphere: "market",
    icon: "👑",
    categories: ["ancient"],
  },
  wuxia: {
    envTheme: "wuxia",
    defaultAtmosphere: "tavern",
    icon: "⚔️",
    categories: ["ancient"],
  },
  demonic_cultivation: {
    envTheme: "demonic",
    defaultAtmosphere: "cave",
    icon: "😈",
    categories: ["ancient"],
  },
  xianxia: {
    envTheme: "ethereal",
    defaultAtmosphere: "mystical",
    icon: "✨",
    categories: ["ancient"],
  },
  infinite_flow: {
    envTheme: "danger",
    defaultAtmosphere: "combat",
    icon: "♾️",
    categories: ["fantasy"],
  },
  entertainment: {
    envTheme: "glamour",
    defaultAtmosphere: "city",
    icon: "🎬",
    categories: ["modern"],
  },
  esports: {
    envTheme: "rgb",
    defaultAtmosphere: "city",
    icon: "🎮",
    categories: ["modern"],
  },
  ceo: {
    envTheme: "modern",
    defaultAtmosphere: "city",
    icon: "💼",
    categories: ["modern"],
  },
  long_aotian: {
    envTheme: "gold",
    defaultAtmosphere: "market",
    icon: "💪",
    categories: ["suspense"],
  },
  villain_op: {
    envTheme: "villain",
    defaultAtmosphere: "horror",
    icon: "🦹",
    categories: ["suspense"],
  },
  period_drama: {
    envTheme: "sepia",
    defaultAtmosphere: "tavern",
    icon: "🎭",
    categories: ["ancient"],
  },
  female_growth: {
    envTheme: "rose",
    defaultAtmosphere: "quiet",
    icon: "🌸",
    categories: ["suspense"],
  },
  war_god: {
    envTheme: "war",
    defaultAtmosphere: "combat",
    icon: "🛡️",
    categories: ["suspense"],
  },
  ancient_romance: {
    envTheme: "sunset",
    defaultAtmosphere: "desert",
    icon: "💖",
    categories: ["ancient"],
  },
  love_after_marriage: {
    envTheme: "romance",
    defaultAtmosphere: "quiet",
    icon: "💍",
    categories: ["modern"],
  },
  angst: {
    envTheme: "cold",
    defaultAtmosphere: "snow",
    icon: "💔",
    categories: ["suspense"],
  },
  reunion: {
    envTheme: "violet",
    defaultAtmosphere: "mystical",
    icon: "🤝",
    categories: ["modern"],
  },
  return_strong: {
    envTheme: "war",
    defaultAtmosphere: "combat",
    icon: "🔥",
    categories: ["suspense"],
  },
  farming: {
    envTheme: "nature",
    defaultAtmosphere: "forest",
    icon: "🌾",
    categories: ["fantasy"],
  },
  republican: {
    envTheme: "artdeco",
    defaultAtmosphere: "city",
    icon: "🎩",
    categories: ["ancient"],
  },
  intrigue: {
    envTheme: "intrigue",
    defaultAtmosphere: "city",
    icon: "🤫",
    categories: ["ancient"],
  },
  survival: {
    envTheme: "wasteland",
    defaultAtmosphere: "desert",
    icon: "🏕️",
    categories: ["suspense"],
  },
  patriotism: {
    envTheme: "patriotic",
    defaultAtmosphere: "combat",
    icon: "🇨🇳",
    categories: ["modern"],
  },
  son_in_law: {
    envTheme: "cyan",
    defaultAtmosphere: "ocean",
    icon: "👨‍👩‍👧",
    categories: ["modern"],
  },
  white_moonlight: {
    envTheme: "silver",
    defaultAtmosphere: "scifi",
    icon: "🌕",
    categories: ["modern"],
  },
  yandere: {
    envTheme: "obsessive",
    defaultAtmosphere: "horror",
    icon: "🔪",
    categories: ["suspense"],
  },
  cs_student: {
    envTheme: "emerald",
    defaultAtmosphere: "forest",
    icon: "💻",
    categories: ["modern"],
  },
  rough_guy: {
    envTheme: "stone",
    defaultAtmosphere: "cave",
    icon: "👊",
    categories: ["modern"],
  },
  wife_chasing: {
    envTheme: "heartbreak",
    defaultAtmosphere: "rain",
    icon: "🏃‍♀️",
    categories: ["modern"],
  },
  special_forces: {
    envTheme: "war",
    defaultAtmosphere: "combat",
    icon: "🎖️",
    categories: ["modern"],
  },
  zombie: {
    envTheme: "apocalypse",
    defaultAtmosphere: "storm",
    icon: "🧟",
    categories: ["suspense"],
  },
  body_swap: {
    envTheme: "modern",
    defaultAtmosphere: "city",
    icon: "👯",
    categories: ["modern"],
  },
  industry_elite: {
    envTheme: "modern",
    defaultAtmosphere: "city",
    icon: "🏢",
    categories: ["modern"],
  },
  mutual_redemption: {
    envTheme: "violet",
    defaultAtmosphere: "mystical",
    icon: "💞",
    categories: ["modern"],
  },
  sweet_pet: {
    envTheme: "romance",
    defaultAtmosphere: "quiet",
    icon: "🍬",
    categories: ["modern"],
  },
  wild_youth: {
    envTheme: "modern",
    defaultAtmosphere: "city",
    icon: "🎸",
    categories: ["modern"],
  },
  rebirth_revenge: {
    envTheme: "intrigue",
    defaultAtmosphere: "city",
    icon: "🩸",
    categories: ["suspense", "modern"],
  },
  flash_marriage: {
    envTheme: "romance",
    defaultAtmosphere: "quiet",
    icon: "⚡",
    categories: ["modern"],
  },
  family_ethics: {
    envTheme: "sepia",
    defaultAtmosphere: "tavern",
    icon: "🏠",
    categories: ["modern"],
  },
  divine_doctor: {
    envTheme: "nature",
    defaultAtmosphere: "forest",
    icon: "💊",
    categories: ["modern", "fantasy"],
  },
  cute_pet: {
    envTheme: "nature",
    defaultAtmosphere: "forest",
    icon: "🐾",
    categories: ["modern", "fantasy"],
  },
  hidden_identity: {
    envTheme: "mystery",
    defaultAtmosphere: "rain",
    icon: "🕶️",
    categories: ["modern", "suspense"],
  },
  system_stream: {
    envTheme: "scifi",
    defaultAtmosphere: "scifi",
    icon: "🤖",
    categories: ["fantasy", "modern"],
  },
  wealthy_family: {
    envTheme: "gold",
    defaultAtmosphere: "market",
    icon: "💰",
    categories: ["modern", "suspense"],
  },
  cs_grad_journey: {
    envTheme: "emerald",
    defaultAtmosphere: "forest",
    icon: "🎓",
    categories: ["modern"],
    restricted: true,
  },
  same_sex_love: {
    envTheme: "romance",
    defaultAtmosphere: "quiet",
    icon: "🏳️‍🌈",
    categories: ["modern", "suspense"],
  },
  minecraft: {
    envTheme: "nature",
    defaultAtmosphere: "forest",
    icon: "⛏️",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  delta_force: {
    envTheme: "war",
    defaultAtmosphere: "combat",
    icon: "🔫",
    categories: ["modern", "game"],
    restricted: true,
  },
  warhammer_40k: {
    envTheme: "war",
    defaultAtmosphere: "combat",
    icon: "💀",
    categories: ["scifi", "game"],
    restricted: true,
  },
  wow: {
    envTheme: "fantasy",
    defaultAtmosphere: "forest",
    icon: "⚔️",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  elder_scrolls: {
    envTheme: "fantasy",
    defaultAtmosphere: "forest",
    icon: "📜",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  dark_souls: {
    envTheme: "gothic",
    defaultAtmosphere: "horror",
    icon: "🔥",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  ninja_gaiden: {
    envTheme: "wuxia",
    defaultAtmosphere: "tavern",
    icon: "🥷",
    categories: ["modern", "game"],
    restricted: true,
  },
  elden_ring: {
    envTheme: "gold",
    defaultAtmosphere: "market",
    icon: "💍",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  stellaris: {
    envTheme: "interstellar",
    defaultAtmosphere: "scifi",
    icon: "🌌",
    categories: ["scifi", "game"],
    restricted: true,
  },
  expedition_33: {
    envTheme: "fantasy",
    defaultAtmosphere: "forest",
    icon: "🧭",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  detroit_become_human: {
    envTheme: "scifi",
    defaultAtmosphere: "scifi",
    icon: "🤖",
    categories: ["scifi", "game"],
    restricted: true,
  },
  witcher: {
    envTheme: "gothic",
    defaultAtmosphere: "horror",
    icon: "🐺",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  dead_space: {
    envTheme: "interstellar",
    defaultAtmosphere: "scifi",
    icon: "👽",
    categories: ["scifi", "game"],
    restricted: true,
  },
  helldivers: {
    envTheme: "war",
    defaultAtmosphere: "combat",
    icon: "🫡",
    categories: ["scifi", "game"],
    restricted: true,
  },
  l4d: {
    envTheme: "apocalypse",
    defaultAtmosphere: "storm",
    icon: "🧟",
    categories: ["modern", "game"],
    restricted: true,
  },
  monster_hunter: {
    envTheme: "fantasy",
    defaultAtmosphere: "forest",
    icon: "🦖",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  warframe: {
    envTheme: "scifi",
    defaultAtmosphere: "scifi",
    icon: "🥷",
    categories: ["scifi", "game"],
    restricted: true,
  },
  lol: {
    envTheme: "fantasy",
    defaultAtmosphere: "forest",
    icon: "🏆",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  terraria: {
    envTheme: "nature",
    defaultAtmosphere: "forest",
    icon: "🌳",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  dnd: {
    envTheme: "fantasy",
    defaultAtmosphere: "forest",
    icon: "🎲",
    categories: ["fantasy", "game"],
    restricted: true,
  },
  mo_dao_zu_shi: {
    envTheme: "wuxia",
    defaultAtmosphere: "tavern",
    icon: "🪈",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  tian_guan_ci_fu: {
    envTheme: "wuxia",
    defaultAtmosphere: "tavern",
    icon: "🦋",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  harry_potter: {
    envTheme: "academy",
    defaultAtmosphere: "quiet",
    icon: "🪄",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  battle_through_heavens: {
    envTheme: "wuxia",
    defaultAtmosphere: "tavern",
    icon: "🔥",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  soul_land: {
    envTheme: "academy",
    defaultAtmosphere: "quiet",
    icon: "🌾",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  xian_ni: {
    envTheme: "wuxia",
    defaultAtmosphere: "tavern",
    icon: "⚡",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  scum_villain: {
    envTheme: "wuxia",
    defaultAtmosphere: "tavern",
    icon: "🥒",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  swallowed_star: {
    envTheme: "interstellar",
    defaultAtmosphere: "scifi",
    icon: "🌌",
    categories: ["scifi", "novel"],
    restricted: true,
  },
  desolate_era: {
    envTheme: "wuxia",
    defaultAtmosphere: "tavern",
    icon: "⚔️",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  mortals_journey: {
    envTheme: "wuxia",
    defaultAtmosphere: "tavern",
    icon: "💊",
    categories: ["wuxia", "novel"],
    restricted: true,
  },
  shepherd_of_gods: {
    envTheme: "fantasy",
    defaultAtmosphere: "forest",
    icon: "🐮",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  frieren: {
    envTheme: "fantasy",
    defaultAtmosphere: "forest",
    icon: "🧝‍♀️",
    categories: ["fantasy", "novel"],
    restricted: true,
  },
  infinite_sequence: {
    envTheme: "interstellar",
    defaultAtmosphere: "scifi",
    icon: "♾️",
    categories: ["scifi", "suspense", "novel"],
    restricted: true,
  },
  kamen_rider: {
    envTheme: "modern",
    defaultAtmosphere: "city",
    icon: "🏍️",
    categories: ["scifi", "movie"],
    restricted: true,
  },
  slay_gods_hospital: {
    envTheme: "modern",
    defaultAtmosphere: "city",
    icon: "🏥",
    categories: ["novel", "modern", "fantasy"],
    restricted: true,
  },
  // New Story Themes - Movies & TV Series
  spartacus: {
    envTheme: "war",
    defaultAtmosphere: "combat",
    icon: "⚔️",
    categories: ["ancient", "movie"],
    restricted: true,
  },
  game_of_thrones: {
    envTheme: "gothic",
    defaultAtmosphere: "horror",
    icon: "🐉",
    categories: ["fantasy", "movie"],
    restricted: true,
  },
  saint_seiya: {
    envTheme: "fantasy",
    defaultAtmosphere: "mystical",
    icon: "⭐",
    categories: ["fantasy", "movie"],
    restricted: true,
  },
  the_conjuring: {
    envTheme: "horror",
    defaultAtmosphere: "horror",
    icon: "👻",
    categories: ["suspense", "movie"],
    restricted: true,
  },
  pennywise: {
    envTheme: "horror",
    defaultAtmosphere: "horror",
    icon: "🎈",
    categories: ["suspense", "movie"],
    restricted: true,
  },
  silent_hill: {
    envTheme: "horror",
    defaultAtmosphere: "horror",
    icon: "🌫️",
    categories: ["suspense", "game", "movie"],
    restricted: true,
  },
  resident_evil: {
    envTheme: "apocalypse",
    defaultAtmosphere: "storm",
    icon: "🧬",
    categories: ["suspense", "game", "movie"],
    restricted: true,
  },
};
